/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.delegate;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.*;
import java.util.concurrent.*;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;

/**
 *
 * <h2>Invoice business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Invoice related services in the case of a Invoice business related service failing.</li>
 * <li>Exposes a simpler, uniform Invoice interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Invoice business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
public class InvoiceBusinessDelegate 
extends BaseBusinessDelegate {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public InvoiceBusinessDelegate()  {
    	projector = new InvoiceEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
				applicationContext.getBean(InvoiceRepository.class) );
	}


   /**
	* Invoice Business Delegate Factory Method
	*
	* All methods are expected to be self-sufficient.
	*
	* @return 	InvoiceBusinessDelegate
	*/
	public static InvoiceBusinessDelegate getInvoiceInstance() {
		return( new InvoiceBusinessDelegate() );
	}
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		Invoice
    */
	public Invoice createInvoice( CreateInvoiceCommand command )
    throws ProcessingException, IllegalArgumentException {

		Invoice entity = new Invoice();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	InvoiceValidator.getInstance().validate( command );    

            entity.setInvoiceId( command.getInvoiceId() );
            entity.setInvoiceNumber( command.getInvoiceNumber() );
            entity.setIssueDate( command.getIssueDate() );
            entity.setDueDate( command.getDueDate() );
            entity.setTotalDue( command.getTotalDue() );
            entity.setStatus( command.getStatus() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.log( Level.INFO, "done creating of Invoice {0} ", entity.toString() );
			
        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Invoice - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateInvoiceCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		Invoice
    */
    public Invoice updateInvoice( UpdateInvoiceCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    Invoice entity = new Invoice();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	InvoiceValidator.getInstance().validate( command );    

            entity.setInvoiceId( command.getInvoiceId() );
            entity.setInvoiceNumber( command.getInvoiceNumber() );
            entity.setIssueDate( command.getIssueDate() );
            entity.setDueDate( command.getDueDate() );
            entity.setTotalDue( command.getTotalDue() );
            entity.setAccount( command.getAccount() );
            entity.setFees( command.getFees() );
            entity.setBillingRun( command.getBillingRun() );
            entity.setStatus( command.getStatus() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.log( Level.INFO, "done saving of Invoice {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Invoice - " + exc;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteInvoiceCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteInvoiceCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	InvoiceValidator.getInstance().validate( command );    
        
        	id = command.getInvoiceId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.log( Level.INFO, "done deleting of Invoice {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Invoice using Id = "  + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the Invoice via InvoiceFetchOneSummary
     * @param 	summary InvoiceFetchOneSummary 
     * @return 	InvoiceFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Invoice getInvoice( InvoiceFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "InvoiceFetchOneSummary arg cannot be null" );
    	
    	Invoice entity = null;
    	UUID id = summary.getInvoiceId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	InvoiceValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a Invoice using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Invoice with id " + id;
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Invoices
     *
     * @return 	List<Invoice> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Invoice> getAllInvoice() 
    throws ProcessingException {
        List<Invoice> list = null;

        try {        	
        	list = projector.findAll( new FindAllInvoiceQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Invoice";
            LOGGER.log( Level.WARNING, errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Account on Invoice
     * @param		command AssignAccountToInvoiceCommand	
     * @exception	ProcessingException
     */     
	public void assignAccount( AssignAccountToInvoiceCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	InvoiceValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignAccount(command.getInvoiceId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Account using id " + command.getInvoiceId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Account on Invoice
     * @param		command UnAssignAccountFromInvoiceCommand
     * @exception	ProcessingException
     */     
	public void unAssignAccount( UnAssignAccountFromInvoiceCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	InvoiceValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignAccount(command.getInvoiceId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Account on Invoice";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign BillingRun on Invoice
     * @param		command AssignBillingRunToInvoiceCommand	
     * @exception	ProcessingException
     */     
	public void assignBillingRun( AssignBillingRunToInvoiceCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	InvoiceValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignBillingRun(command.getInvoiceId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get BillingRun using id " + command.getInvoiceId();
			LOGGER.log( Level.WARNING,  msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign BillingRun on Invoice
     * @param		command UnAssignBillingRunFromInvoiceCommand
     * @exception	ProcessingException
     */     
	public void unAssignBillingRun( UnAssignBillingRunFromInvoiceCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	InvoiceValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignBillingRun(command.getInvoiceId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign BillingRun on Invoice";
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add Fee to Fees 
     * @param		command AssignFeesToInvoiceCommand
     * @exception	ProcessingException
     */     
	public void addToFees( AssignFeesToInvoiceCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	InvoiceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToFees(command.getInvoiceId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Fee as Fees to Invoice" ; 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Fee from Fees
     * @param		command RemoveFeesFromInvoiceCommand
     * @exception	ProcessingException
     */     	
	public void removeFromFees( RemoveFeesFromInvoiceCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	InvoiceValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromFees(command.getInvoiceId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getInvoiceId(); 
			LOGGER.log( Level.WARNING, msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final InvoiceEntityProjector projector;
	private Invoice invoice 	= null;
    private static final Logger LOGGER 			= Logger.getLogger(InvoiceBusinessDelegate.class.getName());
    
}
