/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.projector;

import java.util.*;
import java.util.stream.Collectors;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.PageRequest;
import org.springframework.stereotype.Component;

import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;

/**
 * <h2>OrderEntity Projector</h2>
 * <p>
 * The Order Entity Projector is responsible for maintaining the write model for
 * Order entities. It subscribes to domain events published by the Order
 * Aggregate and updates query-optimized projections used by REST APIs,
 * dashboards, and reporting services.
 * </p>
 * <p>
 * A Projector contains no business logic and never validates commands or
 * modifies the authoritative state of the domain.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *      <ul>
 *          <li>OrderRepository</li>
 *          <li>ProjectorRegistry</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 */
@Component("order-entity-projector")
public class OrderEntityProjector implements EntityProjector<Order>{
		
	// core constructor
	public OrderEntityProjector(ProjectorRegistry registry,
										OrderRepository repository ) {
        this.registry 	= registry;
		this.repository = repository;
    }

	@Override
	public Class<Order> getEntityClass() {
		return Order.class;
	}

    /*
	 * Insert a Order
	 * 
     * @param	entity Order
     */
    public Order create( Order entity) {
	    LOGGER.info("creating " + entity.toString() );
	   
    	// ------------------------------------------
    	// persist a new one
    	// ------------------------------------------ 
	    return repository.save(entity);
        
    }

	/*
	 * Update a Order
	 * 
     * @param	entity Order
     */
    public Order update( Order entity) {
	    LOGGER.info("updating " + entity.toString() );

	    // ------------------------------------------
    	// save with an existing instance
    	// ------------------------------------------ 
		return repository.save(entity);

    }
    
	/*
	 * Delete a Order
	 * 
     * @param	id		UUID
     */
    public Order delete( UUID id ) {
	    LOGGER.info("deleting " + id.toString() );

    	// ------------------------------------------
    	// locate the entity by the provided id
    	// ------------------------------------------
	    Order entity = repository.findById(id).get();
	    
    	// ------------------------------------------
    	// delete what is discovered 
    	// ------------------------------------------
    	repository.delete( entity );
    	
    	return entity;
    }    

    /*
     * Assign a Account
     * 
     * @param	parentId	UUID
     * @param	assignment 	Account 
     * @return	Order
     */
    public Order assignAccount( UUID parentId, Account assignment ) {
	    LOGGER.info("assigning Account as " + assignment.toString() );

	    Order parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Account.class, assignment.getAccountId());

	    // ------------------------------------------
		// assign the Account to the parent entity
		// ------------------------------------------ 
	    parentEntity.setAccount( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Account
	 * 
	 * @param	parentId		UUID
	 * @return	Order
	 */
	public Order unAssignAccount( UUID parentId ) {
		Order parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Account on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Account on the parent entithy
		// ------------------------------------------     
	    parentEntity.setAccount(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Security
     * 
     * @param	parentId	UUID
     * @param	assignment 	Security 
     * @return	Order
     */
    public Order assignSecurity( UUID parentId, Security assignment ) {
	    LOGGER.info("assigning Security as " + assignment.toString() );

	    Order parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Security.class, assignment.getSecurityId());

	    // ------------------------------------------
		// assign the Security to the parent entity
		// ------------------------------------------ 
	    parentEntity.setSecurity( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Security
	 * 
	 * @param	parentId		UUID
	 * @return	Order
	 */
	public Order unAssignSecurity( UUID parentId ) {
		Order parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Security on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Security on the parent entithy
		// ------------------------------------------     
	    parentEntity.setSecurity(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}

    /*
     * Assign a Advisor
     * 
     * @param	parentId	UUID
     * @param	assignment 	Advisor 
     * @return	Order
     */
    public Order assignAdvisor( UUID parentId, Advisor assignment ) {
	    LOGGER.info("assigning Advisor as " + assignment.toString() );

	    Order parentEntity = repository.findById( parentId ).get();
	    assignment = registry.project( Advisor.class, assignment.getAdvisorId());

	    // ------------------------------------------
		// assign the Advisor to the parent entity
		// ------------------------------------------ 
	    parentEntity.setAdvisor( assignment );

	    // ------------------------------------------
    	// save the parent entity
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

	/*
	 * Unassign the Advisor
	 * 
	 * @param	parentId		UUID
	 * @return	Order
	 */
	public Order unAssignAdvisor( UUID parentId ) {
		Order parentEntity = repository.findById(parentId).get();

		LOGGER.info("unAssigning Advisor on " + parentEntity.toString() );
		
	    // ------------------------------------------
		// null out the Advisor on the parent entithy
		// ------------------------------------------     
	    parentEntity.setAdvisor(null);

	    // ------------------------------------------
		// save the parent entity
		// ------------------------------------------ 
	    repository.save(parentEntity);
    
	    return parentEntity;
	}


    /*
     * Add to the Allocations
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Order
     */
    public Order addToAllocations( UUID parentId, OrderAllocation addTo ) {
	    LOGGER.info("handling AssignAllocationsToOrderEvent - " );
	    
	    Order parentEntity = repository.findById(parentId).get();
	    OrderAllocation child = registry.project( OrderAllocation.class, addTo.getOrderAllocationId());
	    
	    parentEntity.getAllocations().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Allocations
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Order
     */
	public Order removeFromAllocations( UUID parentId, OrderAllocation removeFrom ) {
	    LOGGER.info("handling RemoveAllocationsFromOrderEvent " );
	
	    Order parentEntity = repository.findById(parentId).get();
	    OrderAllocation child = registry.project( OrderAllocation.class, removeFrom.getOrderAllocationId());
	    
	    parentEntity.getAllocations().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}

    /*
     * Add to the Trades
     * 
     * @param	parentID	UUID
     * @param	addTo		childType
     * @return	Order
     */
    public Order addToTrades( UUID parentId, Trade addTo ) {
	    LOGGER.info("handling AssignTradesToOrderEvent - " );
	    
	    Order parentEntity = repository.findById(parentId).get();
	    Trade child = registry.project( Trade.class, addTo.getTradeId());
	    
	    parentEntity.getTrades().add( child );

	    // ------------------------------------------
    	// save 
    	// ------------------------------------------ 
	    repository.save(parentEntity);
        
	    return parentEntity;
    }
    

    /*
     * Remove from the Trades
     * 
     * @param	parentID	UUID
     * @param	removeFrom	childType
     * @return	Order
     */
	public Order removeFromTrades( UUID parentId, Trade removeFrom ) {
	    LOGGER.info("handling RemoveTradesFromOrderEvent " );
	
	    Order parentEntity = repository.findById(parentId).get();
	    Trade child = registry.project( Trade.class, removeFrom.getTradeId());
	    
	    parentEntity.getTrades().remove( child );
	
	    // ------------------------------------------
		// save
		// ------------------------------------------ 
	    update(parentEntity);
	    
	    return parentEntity;
	}



    /**
     * Method to retrieve the Order via an FindOrderQuery
     * @return 	query	FindOrderQuery
     */
    @SuppressWarnings("unused")
    public Order find( UUID id ) {
    	LOGGER.info("handling find using " + id.toString() );
    	try {
    		return repository.findById(id).get();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find a Order - {0}", exc.getMessage() );
    	}
    	return null;
    }
    
    /**
     * Method to retrieve a collection of all Orders
     *
     * @param	query	FindAllOrderQuery 
     * @return 	List<Order> 
     */
    @SuppressWarnings("unused")
    public List<Order> findAll( FindAllOrderQuery query ) {
    	LOGGER.info("handling findAll using " + query.toString() );
    	try {
    		return repository.findAll();
    	}
    	catch( IllegalArgumentException exc ) {
    		LOGGER.warn( "Failed to find all Order - {0}", exc.getMessage() );
    	}
    	return null;
    }


    //--------------------------------------------------
    // attributes
    // --------------------------------------------------
	@Autowired
    protected final OrderRepository repository;
	protected final ProjectorRegistry registry;


    private static final Logger LOGGER 	= LoggerFactory.getLogger(OrderEntityProjector.class.getName());

}
