/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>AdvisorValidation</h2>
 * <p>
 * The Advisor Validation  handles state validation of a Advisor include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAdvisorCommand</li>
 *      <li>UpdateAdvisorCommand</li>
 *      <li>DeleteAdvisorCommand</li>
 *set( false = false )
  *       <li>AssignFirmToAdvisorCommand</li>
 *       <li>UnAssignFirmFromAdvisorCommand</li>
  *       <li>AssignOfficeToAdvisorCommand</li>
 *       <li>UnAssignOfficeFromAdvisorCommand</li>
  *       <li>AssignAdvisoryTeamToAdvisorCommand</li>
 *       <li>UnAssignAdvisoryTeamFromAdvisorCommand</li>
   *       <li>AssignClientsToAdvisorCommand</li>
 *       <li>RemoveClientsFromAdvisorCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class AdvisorValidator {
		
	/**
	 * default constructor
	 */
	protected AdvisorValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public AdvisorValidator getInstance() {
		return new AdvisorValidator();
	}
		
	/**
	 * handles creation validation for a Advisor
	 */
	public void validate( CreateAdvisorCommand advisor )throws Exception {
		Assert.notNull( advisor, "CreateAdvisorCommand should not be null" );
//		Assert.isNull( advisor.getAdvisorId(), "CreateAdvisorCommand identifier should be null" );
		Assert.notNull( advisor.getFirstName(), "Field CreateAdvisorCommand.firstName should not be null" );
		Assert.notNull( advisor.getLastName(), "Field CreateAdvisorCommand.lastName should not be null" );
		Assert.notNull( advisor.getLicenseNumber(), "Field CreateAdvisorCommand.licenseNumber should not be null" );
	}

	/**
	 * handles update validation for a Advisor
	 */
	public void validate( UpdateAdvisorCommand advisor ) throws Exception {
		Assert.notNull( advisor, "UpdateAdvisorCommand should not be null" );
		Assert.notNull( advisor.getAdvisorId(), "UpdateAdvisorCommand identifier should not be null" );
		Assert.notNull( advisor.getFirstName(), "Field UpdateAdvisorCommand.firstName should not be null" );
		Assert.notNull( advisor.getLastName(), "Field UpdateAdvisorCommand.lastName should not be null" );
		Assert.notNull( advisor.getLicenseNumber(), "Field UpdateAdvisorCommand.licenseNumber should not be null" );
    }

	/**
	 * handles delete validation for a Advisor
	 */
    public void validate( DeleteAdvisorCommand advisor ) throws Exception {
		Assert.notNull( advisor, "{commandAlias} should not be null" );
		Assert.notNull( advisor.getAdvisorId(), "DeleteAdvisorCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Advisor
	 */
	public void validate( AdvisorFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "AdvisorFetchOneSummary should not be null" );
		Assert.notNull( summary.getAdvisorId(), "AdvisorFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Firm validation for a Advisor
	 * 
	 * @param	command AssignFirmToAdvisorCommand
	 */	
	public void validate( AssignFirmToAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "AssignFirmToAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "AssignFirmToAdvisorCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignFirmToAdvisorCommand assignment should not be null" );
	}

	/**
	 * handles unassign Firm validation for a Advisor
	 * 
	 * @param	command UnAssignFirmFromAdvisorCommand
	 */	
	public void validate( UnAssignFirmFromAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignFirmFromAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "UnAssignFirmFromAdvisorCommand identifier should not be null" );
	}
	/**
	 * handles assign Office validation for a Advisor
	 * 
	 * @param	command AssignOfficeToAdvisorCommand
	 */	
	public void validate( AssignOfficeToAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "AssignOfficeToAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "AssignOfficeToAdvisorCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignOfficeToAdvisorCommand assignment should not be null" );
	}

	/**
	 * handles unassign Office validation for a Advisor
	 * 
	 * @param	command UnAssignOfficeFromAdvisorCommand
	 */	
	public void validate( UnAssignOfficeFromAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignOfficeFromAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "UnAssignOfficeFromAdvisorCommand identifier should not be null" );
	}
	/**
	 * handles assign AdvisoryTeam validation for a Advisor
	 * 
	 * @param	command AssignAdvisoryTeamToAdvisorCommand
	 */	
	public void validate( AssignAdvisoryTeamToAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "AssignAdvisoryTeamToAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "AssignAdvisoryTeamToAdvisorCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAdvisoryTeamToAdvisorCommand assignment should not be null" );
	}

	/**
	 * handles unassign AdvisoryTeam validation for a Advisor
	 * 
	 * @param	command UnAssignAdvisoryTeamFromAdvisorCommand
	 */	
	public void validate( UnAssignAdvisoryTeamFromAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAdvisoryTeamFromAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "UnAssignAdvisoryTeamFromAdvisorCommand identifier should not be null" );
	}

	/**
	 * handles add to Clients validation for a Advisor
	 * 
	 * @param	command AssignClientsToAdvisorCommand
	 */	
	public void validate( AssignClientsToAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "AssignClientsToAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "AssignClientsToAdvisorCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignClientsToAdvisorCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Clients validation for a Advisor
	 * 
	 * @param	command RemoveClientsFromAdvisorCommand
	 */	
	public void validate( RemoveClientsFromAdvisorCommand command ) throws Exception {
		Assert.notNull( command, "RemoveClientsFromAdvisorCommand should not be null" );
		Assert.notNull( command.getAdvisorId(), "RemoveClientsFromAdvisorCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveClientsFromAdvisorCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getClientId(), "RemoveClientsFromAdvisorCommand removeFrom attribubte identifier should not be null" );
	}
	

}
