/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>AssetAllocationSliceValidation</h2>
 * <p>
 * The AssetAllocationSlice Validation  handles state validation of a AssetAllocationSlice include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateAssetAllocationSliceCommand</li>
 *      <li>UpdateAssetAllocationSliceCommand</li>
 *      <li>DeleteAssetAllocationSliceCommand</li>
 *set( false = false )
  *       <li>AssignModelPortfolioToAssetAllocationSliceCommand</li>
 *       <li>UnAssignModelPortfolioFromAssetAllocationSliceCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class AssetAllocationSliceValidator {
		
	/**
	 * default constructor
	 */
	protected AssetAllocationSliceValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public AssetAllocationSliceValidator getInstance() {
		return new AssetAllocationSliceValidator();
	}
		
	/**
	 * handles creation validation for a AssetAllocationSlice
	 */
	public void validate( CreateAssetAllocationSliceCommand assetAllocationSlice )throws Exception {
		Assert.notNull( assetAllocationSlice, "CreateAssetAllocationSliceCommand should not be null" );
//		Assert.isNull( assetAllocationSlice.getAssetAllocationSliceId(), "CreateAssetAllocationSliceCommand identifier should be null" );
		Assert.notNull( assetAllocationSlice.getTargetWeight(), "Field CreateAssetAllocationSliceCommand.targetWeight should not be null" );
	}

	/**
	 * handles update validation for a AssetAllocationSlice
	 */
	public void validate( UpdateAssetAllocationSliceCommand assetAllocationSlice ) throws Exception {
		Assert.notNull( assetAllocationSlice, "UpdateAssetAllocationSliceCommand should not be null" );
		Assert.notNull( assetAllocationSlice.getAssetAllocationSliceId(), "UpdateAssetAllocationSliceCommand identifier should not be null" );
		Assert.notNull( assetAllocationSlice.getTargetWeight(), "Field UpdateAssetAllocationSliceCommand.targetWeight should not be null" );
    }

	/**
	 * handles delete validation for a AssetAllocationSlice
	 */
    public void validate( DeleteAssetAllocationSliceCommand assetAllocationSlice ) throws Exception {
		Assert.notNull( assetAllocationSlice, "{commandAlias} should not be null" );
		Assert.notNull( assetAllocationSlice.getAssetAllocationSliceId(), "DeleteAssetAllocationSliceCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a AssetAllocationSlice
	 */
	public void validate( AssetAllocationSliceFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "AssetAllocationSliceFetchOneSummary should not be null" );
		Assert.notNull( summary.getAssetAllocationSliceId(), "AssetAllocationSliceFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign ModelPortfolio validation for a AssetAllocationSlice
	 * 
	 * @param	command AssignModelPortfolioToAssetAllocationSliceCommand
	 */	
	public void validate( AssignModelPortfolioToAssetAllocationSliceCommand command ) throws Exception {
		Assert.notNull( command, "AssignModelPortfolioToAssetAllocationSliceCommand should not be null" );
		Assert.notNull( command.getAssetAllocationSliceId(), "AssignModelPortfolioToAssetAllocationSliceCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignModelPortfolioToAssetAllocationSliceCommand assignment should not be null" );
	}

	/**
	 * handles unassign ModelPortfolio validation for a AssetAllocationSlice
	 * 
	 * @param	command UnAssignModelPortfolioFromAssetAllocationSliceCommand
	 */	
	public void validate( UnAssignModelPortfolioFromAssetAllocationSliceCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignModelPortfolioFromAssetAllocationSliceCommand should not be null" );
		Assert.notNull( command.getAssetAllocationSliceId(), "UnAssignModelPortfolioFromAssetAllocationSliceCommand identifier should not be null" );
	}


}
