/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>ClientValidation</h2>
 * <p>
 * The Client Validation  handles state validation of a Client include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateClientCommand</li>
 *      <li>UpdateClientCommand</li>
 *      <li>DeleteClientCommand</li>
 *set( false = false )
  *       <li>AssignHouseholdToClientCommand</li>
 *       <li>UnAssignHouseholdFromClientCommand</li>
  *       <li>AssignKycRecordToClientCommand</li>
 *       <li>UnAssignKycRecordFromClientCommand</li>
   *       <li>AssignAccountsToClientCommand</li>
 *       <li>RemoveAccountsFromClientCommand</li>
 *   </ul>
 *
  *       <li>AssignDocumentsToClientCommand</li>
 *       <li>RemoveDocumentsFromClientCommand</li>
 *   </ul>
 *
  *       <li>AssignBeneficiariesToClientCommand</li>
 *       <li>RemoveBeneficiariesFromClientCommand</li>
 *   </ul>
 *
  *       <li>AssignAgreementsToClientCommand</li>
 *       <li>RemoveAgreementsFromClientCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ClientValidator {
		
	/**
	 * default constructor
	 */
	protected ClientValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ClientValidator getInstance() {
		return new ClientValidator();
	}
		
	/**
	 * handles creation validation for a Client
	 */
	public void validate( CreateClientCommand client )throws Exception {
		Assert.notNull( client, "CreateClientCommand should not be null" );
//		Assert.isNull( client.getClientId(), "CreateClientCommand identifier should be null" );
		Assert.notNull( client.getFirstName(), "Field CreateClientCommand.firstName should not be null" );
		Assert.notNull( client.getLastName(), "Field CreateClientCommand.lastName should not be null" );
		Assert.notNull( client.getTaxResidency(), "Field CreateClientCommand.taxResidency should not be null" );
		Assert.notNull( client.getDateOfBirth(), "Field CreateClientCommand.dateOfBirth should not be null" );
		Assert.notNull( client.getEmail(), "Field CreateClientCommand.email should not be null" );
	}

	/**
	 * handles update validation for a Client
	 */
	public void validate( UpdateClientCommand client ) throws Exception {
		Assert.notNull( client, "UpdateClientCommand should not be null" );
		Assert.notNull( client.getClientId(), "UpdateClientCommand identifier should not be null" );
		Assert.notNull( client.getFirstName(), "Field UpdateClientCommand.firstName should not be null" );
		Assert.notNull( client.getLastName(), "Field UpdateClientCommand.lastName should not be null" );
		Assert.notNull( client.getTaxResidency(), "Field UpdateClientCommand.taxResidency should not be null" );
		Assert.notNull( client.getDateOfBirth(), "Field UpdateClientCommand.dateOfBirth should not be null" );
		Assert.notNull( client.getEmail(), "Field UpdateClientCommand.email should not be null" );
    }

	/**
	 * handles delete validation for a Client
	 */
    public void validate( DeleteClientCommand client ) throws Exception {
		Assert.notNull( client, "{commandAlias} should not be null" );
		Assert.notNull( client.getClientId(), "DeleteClientCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Client
	 */
	public void validate( ClientFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ClientFetchOneSummary should not be null" );
		Assert.notNull( summary.getClientId(), "ClientFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Household validation for a Client
	 * 
	 * @param	command AssignHouseholdToClientCommand
	 */	
	public void validate( AssignHouseholdToClientCommand command ) throws Exception {
		Assert.notNull( command, "AssignHouseholdToClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "AssignHouseholdToClientCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignHouseholdToClientCommand assignment should not be null" );
	}

	/**
	 * handles unassign Household validation for a Client
	 * 
	 * @param	command UnAssignHouseholdFromClientCommand
	 */	
	public void validate( UnAssignHouseholdFromClientCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignHouseholdFromClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "UnAssignHouseholdFromClientCommand identifier should not be null" );
	}
	/**
	 * handles assign KycRecord validation for a Client
	 * 
	 * @param	command AssignKycRecordToClientCommand
	 */	
	public void validate( AssignKycRecordToClientCommand command ) throws Exception {
		Assert.notNull( command, "AssignKycRecordToClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "AssignKycRecordToClientCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignKycRecordToClientCommand assignment should not be null" );
	}

	/**
	 * handles unassign KycRecord validation for a Client
	 * 
	 * @param	command UnAssignKycRecordFromClientCommand
	 */	
	public void validate( UnAssignKycRecordFromClientCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignKycRecordFromClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "UnAssignKycRecordFromClientCommand identifier should not be null" );
	}

	/**
	 * handles add to Accounts validation for a Client
	 * 
	 * @param	command AssignAccountsToClientCommand
	 */	
	public void validate( AssignAccountsToClientCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountsToClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "AssignAccountsToClientCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAccountsToClientCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Accounts validation for a Client
	 * 
	 * @param	command RemoveAccountsFromClientCommand
	 */	
	public void validate( RemoveAccountsFromClientCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAccountsFromClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "RemoveAccountsFromClientCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAccountsFromClientCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAccountId(), "RemoveAccountsFromClientCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Documents validation for a Client
	 * 
	 * @param	command AssignDocumentsToClientCommand
	 */	
	public void validate( AssignDocumentsToClientCommand command ) throws Exception {
		Assert.notNull( command, "AssignDocumentsToClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "AssignDocumentsToClientCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDocumentsToClientCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Documents validation for a Client
	 * 
	 * @param	command RemoveDocumentsFromClientCommand
	 */	
	public void validate( RemoveDocumentsFromClientCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDocumentsFromClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "RemoveDocumentsFromClientCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDocumentsFromClientCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDocumentId(), "RemoveDocumentsFromClientCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Beneficiaries validation for a Client
	 * 
	 * @param	command AssignBeneficiariesToClientCommand
	 */	
	public void validate( AssignBeneficiariesToClientCommand command ) throws Exception {
		Assert.notNull( command, "AssignBeneficiariesToClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "AssignBeneficiariesToClientCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignBeneficiariesToClientCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Beneficiaries validation for a Client
	 * 
	 * @param	command RemoveBeneficiariesFromClientCommand
	 */	
	public void validate( RemoveBeneficiariesFromClientCommand command ) throws Exception {
		Assert.notNull( command, "RemoveBeneficiariesFromClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "RemoveBeneficiariesFromClientCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveBeneficiariesFromClientCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getBeneficiaryId(), "RemoveBeneficiariesFromClientCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Agreements validation for a Client
	 * 
	 * @param	command AssignAgreementsToClientCommand
	 */	
	public void validate( AssignAgreementsToClientCommand command ) throws Exception {
		Assert.notNull( command, "AssignAgreementsToClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "AssignAgreementsToClientCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAgreementsToClientCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Agreements validation for a Client
	 * 
	 * @param	command RemoveAgreementsFromClientCommand
	 */	
	public void validate( RemoveAgreementsFromClientCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAgreementsFromClientCommand should not be null" );
		Assert.notNull( command.getClientId(), "RemoveAgreementsFromClientCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAgreementsFromClientCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAgreementId(), "RemoveAgreementsFromClientCommand removeFrom attribubte identifier should not be null" );
	}
	

}
