/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
		package com.harbormaster.validator;

import org.springframework.stereotype.Component;
import org.springframework.util.Assert;

import com.harbormaster.api.*;
import com.harbormaster.exception.*;

/**
 * <h2>ComplianceRuleValidation</h2>
 * <p>
 * The ComplianceRule Validation  handles state validation of a ComplianceRule include direct attributes and single/multiple associations.
 * </p>
 #generatedFrom()
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateComplianceRuleCommand</li>
 *      <li>UpdateComplianceRuleCommand</li>
 *      <li>DeleteComplianceRuleCommand</li>
 *set( false = false )
   *       <li>AssignAlertsToComplianceRuleCommand</li>
 *       <li>RemoveAlertsFromComplianceRuleCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
@Component
public class ComplianceRuleValidator {

	/**
	 * default constructor
	 */
	protected ComplianceRuleValidator() {
	}


	/**
	 * handles creation validation for a ComplianceRule
	 */
	public void validate( CreateComplianceRuleCommand complianceRule )throws ValidationException {
		if ( complianceRule == null )
		throw new ValidationException( "ComplianceRule", "validating CreateComplianceRuleCommand" );
		if ( complianceRule.getName() == null )
		throw new ValidationException( "ComplianceRule", "validating access on getName" );
		if ( complianceRule.getRuleCode() == null )
		throw new ValidationException( "ComplianceRule", "validating access on getRuleCode" );
		if ( complianceRule.getDescription() == null )
		throw new ValidationException( "ComplianceRule", "validating access on getDescription" );
	}

	/**
	 * handles update validation for a ComplianceRule
	 */
	public void validate( UpdateComplianceRuleCommand complianceRule ) throws ValidationException {
		if ( complianceRule == null )
		throw new ValidationException( "ComplianceRule", "validating UpdateComplianceRuleCommand" );
		if ( complianceRule.getName() == null )
		throw new ValidationException( "ComplianceRule", "validating method getName" );
		if ( complianceRule.getRuleCode() == null )
		throw new ValidationException( "ComplianceRule", "validating method getRuleCode" );
		if ( complianceRule.getDescription() == null )
		throw new ValidationException( "ComplianceRule", "validating method getDescription" );
	}

/**
 * handles delete validation for a ComplianceRule
 */
	public void validate( DeleteComplianceRuleCommand complianceRule ) throws ValidationException {
		if ( complianceRule == null )
			throw new ValidationException( "ComplianceRule", "validating DeleteComplianceRuleCommand" );
	}

/**
 * handles fetchOne validation for a ComplianceRule
 */
	public void validate( ComplianceRuleFetchOneSummary summary ) throws ValidationException {
		if ( summary == null )
			throw new ValidationException( "ComplianceRule", "validating summary" );
	}


	/**
	 * handles add to Alerts validation for a ComplianceRule
	 *
	 * @param	command AssignAlertsToComplianceRuleCommand
	 */
	public void validate( AssignAlertsToComplianceRuleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException( "ComplianceRule", "validating AssignAlertsToComplianceRuleCommand" );

		if ( command.getComplianceRuleId() == null )
		throw new ValidationException( "ComplianceRule", "validating identity on AssignAlertsToComplianceRuleCommand" );

		if ( command.getAddTo() == null )
			throw new ValidationException( "ComplianceRule", "validating addTo attribute on AssignAlertsToComplianceRuleCommand" );

	}

	/**
	 * handles remove from Alerts validation for a ComplianceRule
	 *
	 * @param	command RemoveAlertsFromComplianceRuleCommand
	 */
	public void validate( RemoveAlertsFromComplianceRuleCommand command ) throws ValidationException {
		if ( command == null )
			throw new ValidationException("ComplianceRule", "validating RemoveAlertsFromComplianceRuleCommand" );

		if( command.getComplianceRuleId() == null )
			throw new ValidationException("ComplianceRule", "validating id on RemoveAlertsFromComplianceRuleCommand" );

		if( command.getRemoveFrom() == null )
			throw new ValidationException("ComplianceRule", "validating remove from RemoveAlertsFromComplianceRuleCommand" );

		if( command.getRemoveFrom().getComplianceAlertId() == null )
			throw new ValidationException("ComplianceRule", "validating id on remove from RemoveAlertsFromComplianceRuleCommand" );
	}


}
