/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>ComplianceAlertValidation</h2>
 * <p>
 * The ComplianceAlert Validation  handles state validation of a ComplianceAlert include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateComplianceAlertCommand</li>
 *      <li>UpdateComplianceAlertCommand</li>
 *      <li>DeleteComplianceAlertCommand</li>
 *set( false = false )
  *       <li>AssignRuleToComplianceAlertCommand</li>
 *       <li>UnAssignRuleFromComplianceAlertCommand</li>
  *       <li>AssignAccountToComplianceAlertCommand</li>
 *       <li>UnAssignAccountFromComplianceAlertCommand</li>
  *       <li>AssignOrderToComplianceAlertCommand</li>
 *       <li>UnAssignOrderFromComplianceAlertCommand</li>
  *       <li>AssignAdvisorToComplianceAlertCommand</li>
 *       <li>UnAssignAdvisorFromComplianceAlertCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ComplianceAlertValidator {
		
	/**
	 * default constructor
	 */
	protected ComplianceAlertValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ComplianceAlertValidator getInstance() {
		return new ComplianceAlertValidator();
	}
		
	/**
	 * handles creation validation for a ComplianceAlert
	 */
	public void validate( CreateComplianceAlertCommand complianceAlert )throws Exception {
		Assert.notNull( complianceAlert, "CreateComplianceAlertCommand should not be null" );
//		Assert.isNull( complianceAlert.getComplianceAlertId(), "CreateComplianceAlertCommand identifier should be null" );
		Assert.notNull( complianceAlert.getAlertDate(), "Field CreateComplianceAlertCommand.alertDate should not be null" );
		Assert.notNull( complianceAlert.getMessage(), "Field CreateComplianceAlertCommand.message should not be null" );
	}

	/**
	 * handles update validation for a ComplianceAlert
	 */
	public void validate( UpdateComplianceAlertCommand complianceAlert ) throws Exception {
		Assert.notNull( complianceAlert, "UpdateComplianceAlertCommand should not be null" );
		Assert.notNull( complianceAlert.getComplianceAlertId(), "UpdateComplianceAlertCommand identifier should not be null" );
		Assert.notNull( complianceAlert.getAlertDate(), "Field UpdateComplianceAlertCommand.alertDate should not be null" );
		Assert.notNull( complianceAlert.getMessage(), "Field UpdateComplianceAlertCommand.message should not be null" );
    }

	/**
	 * handles delete validation for a ComplianceAlert
	 */
    public void validate( DeleteComplianceAlertCommand complianceAlert ) throws Exception {
		Assert.notNull( complianceAlert, "{commandAlias} should not be null" );
		Assert.notNull( complianceAlert.getComplianceAlertId(), "DeleteComplianceAlertCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a ComplianceAlert
	 */
	public void validate( ComplianceAlertFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ComplianceAlertFetchOneSummary should not be null" );
		Assert.notNull( summary.getComplianceAlertId(), "ComplianceAlertFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Rule validation for a ComplianceAlert
	 * 
	 * @param	command AssignRuleToComplianceAlertCommand
	 */	
	public void validate( AssignRuleToComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignRuleToComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "AssignRuleToComplianceAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignRuleToComplianceAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Rule validation for a ComplianceAlert
	 * 
	 * @param	command UnAssignRuleFromComplianceAlertCommand
	 */	
	public void validate( UnAssignRuleFromComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignRuleFromComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "UnAssignRuleFromComplianceAlertCommand identifier should not be null" );
	}
	/**
	 * handles assign Account validation for a ComplianceAlert
	 * 
	 * @param	command AssignAccountToComplianceAlertCommand
	 */	
	public void validate( AssignAccountToComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "AssignAccountToComplianceAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToComplianceAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a ComplianceAlert
	 * 
	 * @param	command UnAssignAccountFromComplianceAlertCommand
	 */	
	public void validate( UnAssignAccountFromComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "UnAssignAccountFromComplianceAlertCommand identifier should not be null" );
	}
	/**
	 * handles assign Order validation for a ComplianceAlert
	 * 
	 * @param	command AssignOrderToComplianceAlertCommand
	 */	
	public void validate( AssignOrderToComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignOrderToComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "AssignOrderToComplianceAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignOrderToComplianceAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Order validation for a ComplianceAlert
	 * 
	 * @param	command UnAssignOrderFromComplianceAlertCommand
	 */	
	public void validate( UnAssignOrderFromComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignOrderFromComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "UnAssignOrderFromComplianceAlertCommand identifier should not be null" );
	}
	/**
	 * handles assign Advisor validation for a ComplianceAlert
	 * 
	 * @param	command AssignAdvisorToComplianceAlertCommand
	 */	
	public void validate( AssignAdvisorToComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "AssignAdvisorToComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "AssignAdvisorToComplianceAlertCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAdvisorToComplianceAlertCommand assignment should not be null" );
	}

	/**
	 * handles unassign Advisor validation for a ComplianceAlert
	 * 
	 * @param	command UnAssignAdvisorFromComplianceAlertCommand
	 */	
	public void validate( UnAssignAdvisorFromComplianceAlertCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAdvisorFromComplianceAlertCommand should not be null" );
		Assert.notNull( command.getComplianceAlertId(), "UnAssignAdvisorFromComplianceAlertCommand identifier should not be null" );
	}


}
