/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>CorporateActionValidation</h2>
 * <p>
 * The CorporateAction Validation  handles state validation of a CorporateAction include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateCorporateActionCommand</li>
 *      <li>UpdateCorporateActionCommand</li>
 *      <li>DeleteCorporateActionCommand</li>
 *set( false = false )
  *       <li>AssignSecurityToCorporateActionCommand</li>
 *       <li>UnAssignSecurityFromCorporateActionCommand</li>
   *       <li>AssignDividendsToCorporateActionCommand</li>
 *       <li>RemoveDividendsFromCorporateActionCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class CorporateActionValidator {
		
	/**
	 * default constructor
	 */
	protected CorporateActionValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public CorporateActionValidator getInstance() {
		return new CorporateActionValidator();
	}
		
	/**
	 * handles creation validation for a CorporateAction
	 */
	public void validate( CreateCorporateActionCommand corporateAction )throws Exception {
		Assert.notNull( corporateAction, "CreateCorporateActionCommand should not be null" );
//		Assert.isNull( corporateAction.getCorporateActionId(), "CreateCorporateActionCommand identifier should be null" );
		Assert.notNull( corporateAction.getRecordDate(), "Field CreateCorporateActionCommand.recordDate should not be null" );
		Assert.notNull( corporateAction.getPayableDate(), "Field CreateCorporateActionCommand.payableDate should not be null" );
		Assert.notNull( corporateAction.getDetails(), "Field CreateCorporateActionCommand.details should not be null" );
	}

	/**
	 * handles update validation for a CorporateAction
	 */
	public void validate( UpdateCorporateActionCommand corporateAction ) throws Exception {
		Assert.notNull( corporateAction, "UpdateCorporateActionCommand should not be null" );
		Assert.notNull( corporateAction.getCorporateActionId(), "UpdateCorporateActionCommand identifier should not be null" );
		Assert.notNull( corporateAction.getRecordDate(), "Field UpdateCorporateActionCommand.recordDate should not be null" );
		Assert.notNull( corporateAction.getPayableDate(), "Field UpdateCorporateActionCommand.payableDate should not be null" );
		Assert.notNull( corporateAction.getDetails(), "Field UpdateCorporateActionCommand.details should not be null" );
    }

	/**
	 * handles delete validation for a CorporateAction
	 */
    public void validate( DeleteCorporateActionCommand corporateAction ) throws Exception {
		Assert.notNull( corporateAction, "{commandAlias} should not be null" );
		Assert.notNull( corporateAction.getCorporateActionId(), "DeleteCorporateActionCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a CorporateAction
	 */
	public void validate( CorporateActionFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "CorporateActionFetchOneSummary should not be null" );
		Assert.notNull( summary.getCorporateActionId(), "CorporateActionFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Security validation for a CorporateAction
	 * 
	 * @param	command AssignSecurityToCorporateActionCommand
	 */	
	public void validate( AssignSecurityToCorporateActionCommand command ) throws Exception {
		Assert.notNull( command, "AssignSecurityToCorporateActionCommand should not be null" );
		Assert.notNull( command.getCorporateActionId(), "AssignSecurityToCorporateActionCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignSecurityToCorporateActionCommand assignment should not be null" );
	}

	/**
	 * handles unassign Security validation for a CorporateAction
	 * 
	 * @param	command UnAssignSecurityFromCorporateActionCommand
	 */	
	public void validate( UnAssignSecurityFromCorporateActionCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignSecurityFromCorporateActionCommand should not be null" );
		Assert.notNull( command.getCorporateActionId(), "UnAssignSecurityFromCorporateActionCommand identifier should not be null" );
	}

	/**
	 * handles add to Dividends validation for a CorporateAction
	 * 
	 * @param	command AssignDividendsToCorporateActionCommand
	 */	
	public void validate( AssignDividendsToCorporateActionCommand command ) throws Exception {
		Assert.notNull( command, "AssignDividendsToCorporateActionCommand should not be null" );
		Assert.notNull( command.getCorporateActionId(), "AssignDividendsToCorporateActionCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignDividendsToCorporateActionCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Dividends validation for a CorporateAction
	 * 
	 * @param	command RemoveDividendsFromCorporateActionCommand
	 */	
	public void validate( RemoveDividendsFromCorporateActionCommand command ) throws Exception {
		Assert.notNull( command, "RemoveDividendsFromCorporateActionCommand should not be null" );
		Assert.notNull( command.getCorporateActionId(), "RemoveDividendsFromCorporateActionCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveDividendsFromCorporateActionCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getDividendId(), "RemoveDividendsFromCorporateActionCommand removeFrom attribubte identifier should not be null" );
	}
	

}
