/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>DividendValidation</h2>
 * <p>
 * The Dividend Validation  handles state validation of a Dividend include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateDividendCommand</li>
 *      <li>UpdateDividendCommand</li>
 *      <li>DeleteDividendCommand</li>
 *set( false = false )
  *       <li>AssignCorporateActionToDividendCommand</li>
 *       <li>UnAssignCorporateActionFromDividendCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class DividendValidator {
		
	/**
	 * default constructor
	 */
	protected DividendValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public DividendValidator getInstance() {
		return new DividendValidator();
	}
		
	/**
	 * handles creation validation for a Dividend
	 */
	public void validate( CreateDividendCommand dividend )throws Exception {
		Assert.notNull( dividend, "CreateDividendCommand should not be null" );
//		Assert.isNull( dividend.getDividendId(), "CreateDividendCommand identifier should be null" );
		Assert.notNull( dividend.getGrossAmount(), "Field CreateDividendCommand.grossAmount should not be null" );
		Assert.notNull( dividend.getTaxWithheld(), "Field CreateDividendCommand.taxWithheld should not be null" );
	}

	/**
	 * handles update validation for a Dividend
	 */
	public void validate( UpdateDividendCommand dividend ) throws Exception {
		Assert.notNull( dividend, "UpdateDividendCommand should not be null" );
		Assert.notNull( dividend.getDividendId(), "UpdateDividendCommand identifier should not be null" );
		Assert.notNull( dividend.getGrossAmount(), "Field UpdateDividendCommand.grossAmount should not be null" );
		Assert.notNull( dividend.getTaxWithheld(), "Field UpdateDividendCommand.taxWithheld should not be null" );
    }

	/**
	 * handles delete validation for a Dividend
	 */
    public void validate( DeleteDividendCommand dividend ) throws Exception {
		Assert.notNull( dividend, "{commandAlias} should not be null" );
		Assert.notNull( dividend.getDividendId(), "DeleteDividendCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Dividend
	 */
	public void validate( DividendFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "DividendFetchOneSummary should not be null" );
		Assert.notNull( summary.getDividendId(), "DividendFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign CorporateAction validation for a Dividend
	 * 
	 * @param	command AssignCorporateActionToDividendCommand
	 */	
	public void validate( AssignCorporateActionToDividendCommand command ) throws Exception {
		Assert.notNull( command, "AssignCorporateActionToDividendCommand should not be null" );
		Assert.notNull( command.getDividendId(), "AssignCorporateActionToDividendCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignCorporateActionToDividendCommand assignment should not be null" );
	}

	/**
	 * handles unassign CorporateAction validation for a Dividend
	 * 
	 * @param	command UnAssignCorporateActionFromDividendCommand
	 */	
	public void validate( UnAssignCorporateActionFromDividendCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignCorporateActionFromDividendCommand should not be null" );
		Assert.notNull( command.getDividendId(), "UnAssignCorporateActionFromDividendCommand identifier should not be null" );
	}


}
