/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>DocumentValidation</h2>
 * <p>
 * The Document Validation  handles state validation of a Document include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateDocumentCommand</li>
 *      <li>UpdateDocumentCommand</li>
 *      <li>DeleteDocumentCommand</li>
 *set( false = false )
  *       <li>AssignClientToDocumentCommand</li>
 *       <li>UnAssignClientFromDocumentCommand</li>
  *       <li>AssignKycRecordToDocumentCommand</li>
 *       <li>UnAssignKycRecordFromDocumentCommand</li>
  *       <li>AssignAgreementToDocumentCommand</li>
 *       <li>UnAssignAgreementFromDocumentCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class DocumentValidator {
		
	/**
	 * default constructor
	 */
	protected DocumentValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public DocumentValidator getInstance() {
		return new DocumentValidator();
	}
		
	/**
	 * handles creation validation for a Document
	 */
	public void validate( CreateDocumentCommand document )throws Exception {
		Assert.notNull( document, "CreateDocumentCommand should not be null" );
//		Assert.isNull( document.getDocumentId(), "CreateDocumentCommand identifier should be null" );
		Assert.notNull( document.getTitle(), "Field CreateDocumentCommand.title should not be null" );
		Assert.notNull( document.getFileName(), "Field CreateDocumentCommand.fileName should not be null" );
		Assert.notNull( document.getReceivedDate(), "Field CreateDocumentCommand.receivedDate should not be null" );
	}

	/**
	 * handles update validation for a Document
	 */
	public void validate( UpdateDocumentCommand document ) throws Exception {
		Assert.notNull( document, "UpdateDocumentCommand should not be null" );
		Assert.notNull( document.getDocumentId(), "UpdateDocumentCommand identifier should not be null" );
		Assert.notNull( document.getTitle(), "Field UpdateDocumentCommand.title should not be null" );
		Assert.notNull( document.getFileName(), "Field UpdateDocumentCommand.fileName should not be null" );
		Assert.notNull( document.getReceivedDate(), "Field UpdateDocumentCommand.receivedDate should not be null" );
    }

	/**
	 * handles delete validation for a Document
	 */
    public void validate( DeleteDocumentCommand document ) throws Exception {
		Assert.notNull( document, "{commandAlias} should not be null" );
		Assert.notNull( document.getDocumentId(), "DeleteDocumentCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Document
	 */
	public void validate( DocumentFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "DocumentFetchOneSummary should not be null" );
		Assert.notNull( summary.getDocumentId(), "DocumentFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Client validation for a Document
	 * 
	 * @param	command AssignClientToDocumentCommand
	 */	
	public void validate( AssignClientToDocumentCommand command ) throws Exception {
		Assert.notNull( command, "AssignClientToDocumentCommand should not be null" );
		Assert.notNull( command.getDocumentId(), "AssignClientToDocumentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignClientToDocumentCommand assignment should not be null" );
	}

	/**
	 * handles unassign Client validation for a Document
	 * 
	 * @param	command UnAssignClientFromDocumentCommand
	 */	
	public void validate( UnAssignClientFromDocumentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignClientFromDocumentCommand should not be null" );
		Assert.notNull( command.getDocumentId(), "UnAssignClientFromDocumentCommand identifier should not be null" );
	}
	/**
	 * handles assign KycRecord validation for a Document
	 * 
	 * @param	command AssignKycRecordToDocumentCommand
	 */	
	public void validate( AssignKycRecordToDocumentCommand command ) throws Exception {
		Assert.notNull( command, "AssignKycRecordToDocumentCommand should not be null" );
		Assert.notNull( command.getDocumentId(), "AssignKycRecordToDocumentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignKycRecordToDocumentCommand assignment should not be null" );
	}

	/**
	 * handles unassign KycRecord validation for a Document
	 * 
	 * @param	command UnAssignKycRecordFromDocumentCommand
	 */	
	public void validate( UnAssignKycRecordFromDocumentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignKycRecordFromDocumentCommand should not be null" );
		Assert.notNull( command.getDocumentId(), "UnAssignKycRecordFromDocumentCommand identifier should not be null" );
	}
	/**
	 * handles assign Agreement validation for a Document
	 * 
	 * @param	command AssignAgreementToDocumentCommand
	 */	
	public void validate( AssignAgreementToDocumentCommand command ) throws Exception {
		Assert.notNull( command, "AssignAgreementToDocumentCommand should not be null" );
		Assert.notNull( command.getDocumentId(), "AssignAgreementToDocumentCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAgreementToDocumentCommand assignment should not be null" );
	}

	/**
	 * handles unassign Agreement validation for a Document
	 * 
	 * @param	command UnAssignAgreementFromDocumentCommand
	 */	
	public void validate( UnAssignAgreementFromDocumentCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAgreementFromDocumentCommand should not be null" );
		Assert.notNull( command.getDocumentId(), "UnAssignAgreementFromDocumentCommand identifier should not be null" );
	}


}
