/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>HouseholdValidation</h2>
 * <p>
 * The Household Validation  handles state validation of a Household include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateHouseholdCommand</li>
 *      <li>UpdateHouseholdCommand</li>
 *      <li>DeleteHouseholdCommand</li>
 *set( false = false )
  *       <li>AssignPrimaryAdvisorToHouseholdCommand</li>
 *       <li>UnAssignPrimaryAdvisorFromHouseholdCommand</li>
   *       <li>AssignClientsToHouseholdCommand</li>
 *       <li>RemoveClientsFromHouseholdCommand</li>
 *   </ul>
 *
  *       <li>AssignPortfoliosToHouseholdCommand</li>
 *       <li>RemovePortfoliosFromHouseholdCommand</li>
 *   </ul>
 *
  *       <li>AssignGoalsToHouseholdCommand</li>
 *       <li>RemoveGoalsFromHouseholdCommand</li>
 *   </ul>
 *
  *       <li>AssignRiskAssessmentsToHouseholdCommand</li>
 *       <li>RemoveRiskAssessmentsFromHouseholdCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class HouseholdValidator {
		
	/**
	 * default constructor
	 */
	protected HouseholdValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public HouseholdValidator getInstance() {
		return new HouseholdValidator();
	}
		
	/**
	 * handles creation validation for a Household
	 */
	public void validate( CreateHouseholdCommand household )throws Exception {
		Assert.notNull( household, "CreateHouseholdCommand should not be null" );
//		Assert.isNull( household.getHouseholdId(), "CreateHouseholdCommand identifier should be null" );
		Assert.notNull( household.getName(), "Field CreateHouseholdCommand.name should not be null" );
	}

	/**
	 * handles update validation for a Household
	 */
	public void validate( UpdateHouseholdCommand household ) throws Exception {
		Assert.notNull( household, "UpdateHouseholdCommand should not be null" );
		Assert.notNull( household.getHouseholdId(), "UpdateHouseholdCommand identifier should not be null" );
		Assert.notNull( household.getName(), "Field UpdateHouseholdCommand.name should not be null" );
    }

	/**
	 * handles delete validation for a Household
	 */
    public void validate( DeleteHouseholdCommand household ) throws Exception {
		Assert.notNull( household, "{commandAlias} should not be null" );
		Assert.notNull( household.getHouseholdId(), "DeleteHouseholdCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Household
	 */
	public void validate( HouseholdFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "HouseholdFetchOneSummary should not be null" );
		Assert.notNull( summary.getHouseholdId(), "HouseholdFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign PrimaryAdvisor validation for a Household
	 * 
	 * @param	command AssignPrimaryAdvisorToHouseholdCommand
	 */	
	public void validate( AssignPrimaryAdvisorToHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "AssignPrimaryAdvisorToHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "AssignPrimaryAdvisorToHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPrimaryAdvisorToHouseholdCommand assignment should not be null" );
	}

	/**
	 * handles unassign PrimaryAdvisor validation for a Household
	 * 
	 * @param	command UnAssignPrimaryAdvisorFromHouseholdCommand
	 */	
	public void validate( UnAssignPrimaryAdvisorFromHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPrimaryAdvisorFromHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "UnAssignPrimaryAdvisorFromHouseholdCommand identifier should not be null" );
	}

	/**
	 * handles add to Clients validation for a Household
	 * 
	 * @param	command AssignClientsToHouseholdCommand
	 */	
	public void validate( AssignClientsToHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "AssignClientsToHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "AssignClientsToHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignClientsToHouseholdCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Clients validation for a Household
	 * 
	 * @param	command RemoveClientsFromHouseholdCommand
	 */	
	public void validate( RemoveClientsFromHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "RemoveClientsFromHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "RemoveClientsFromHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveClientsFromHouseholdCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getClientId(), "RemoveClientsFromHouseholdCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Portfolios validation for a Household
	 * 
	 * @param	command AssignPortfoliosToHouseholdCommand
	 */	
	public void validate( AssignPortfoliosToHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "AssignPortfoliosToHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "AssignPortfoliosToHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignPortfoliosToHouseholdCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Portfolios validation for a Household
	 * 
	 * @param	command RemovePortfoliosFromHouseholdCommand
	 */	
	public void validate( RemovePortfoliosFromHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "RemovePortfoliosFromHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "RemovePortfoliosFromHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemovePortfoliosFromHouseholdCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getPortfolioId(), "RemovePortfoliosFromHouseholdCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Goals validation for a Household
	 * 
	 * @param	command AssignGoalsToHouseholdCommand
	 */	
	public void validate( AssignGoalsToHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "AssignGoalsToHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "AssignGoalsToHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignGoalsToHouseholdCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Goals validation for a Household
	 * 
	 * @param	command RemoveGoalsFromHouseholdCommand
	 */	
	public void validate( RemoveGoalsFromHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "RemoveGoalsFromHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "RemoveGoalsFromHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveGoalsFromHouseholdCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getWealthGoalId(), "RemoveGoalsFromHouseholdCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to RiskAssessments validation for a Household
	 * 
	 * @param	command AssignRiskAssessmentsToHouseholdCommand
	 */	
	public void validate( AssignRiskAssessmentsToHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "AssignRiskAssessmentsToHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "AssignRiskAssessmentsToHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignRiskAssessmentsToHouseholdCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from RiskAssessments validation for a Household
	 * 
	 * @param	command RemoveRiskAssessmentsFromHouseholdCommand
	 */	
	public void validate( RemoveRiskAssessmentsFromHouseholdCommand command ) throws Exception {
		Assert.notNull( command, "RemoveRiskAssessmentsFromHouseholdCommand should not be null" );
		Assert.notNull( command.getHouseholdId(), "RemoveRiskAssessmentsFromHouseholdCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveRiskAssessmentsFromHouseholdCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getRiskAssessmentId(), "RemoveRiskAssessmentsFromHouseholdCommand removeFrom attribubte identifier should not be null" );
	}
	

}
