/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>InvestmentPolicyValidation</h2>
 * <p>
 * The InvestmentPolicy Validation  handles state validation of a InvestmentPolicy include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateInvestmentPolicyCommand</li>
 *      <li>UpdateInvestmentPolicyCommand</li>
 *      <li>DeleteInvestmentPolicyCommand</li>
 *set( false = false )
  *       <li>AssignPortfolioToInvestmentPolicyCommand</li>
 *       <li>UnAssignPortfolioFromInvestmentPolicyCommand</li>
  *       <li>AssignRiskAssessmentToInvestmentPolicyCommand</li>
 *       <li>UnAssignRiskAssessmentFromInvestmentPolicyCommand</li>
   *       <li>AssignGoalsToInvestmentPolicyCommand</li>
 *       <li>RemoveGoalsFromInvestmentPolicyCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class InvestmentPolicyValidator {
		
	/**
	 * default constructor
	 */
	protected InvestmentPolicyValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public InvestmentPolicyValidator getInstance() {
		return new InvestmentPolicyValidator();
	}
		
	/**
	 * handles creation validation for a InvestmentPolicy
	 */
	public void validate( CreateInvestmentPolicyCommand investmentPolicy )throws Exception {
		Assert.notNull( investmentPolicy, "CreateInvestmentPolicyCommand should not be null" );
//		Assert.isNull( investmentPolicy.getInvestmentPolicyId(), "CreateInvestmentPolicyCommand identifier should be null" );
		Assert.notNull( investmentPolicy.getPolicyNumber(), "Field CreateInvestmentPolicyCommand.policyNumber should not be null" );
		Assert.notNull( investmentPolicy.getConstraints(), "Field CreateInvestmentPolicyCommand.constraints should not be null" );
	}

	/**
	 * handles update validation for a InvestmentPolicy
	 */
	public void validate( UpdateInvestmentPolicyCommand investmentPolicy ) throws Exception {
		Assert.notNull( investmentPolicy, "UpdateInvestmentPolicyCommand should not be null" );
		Assert.notNull( investmentPolicy.getInvestmentPolicyId(), "UpdateInvestmentPolicyCommand identifier should not be null" );
		Assert.notNull( investmentPolicy.getPolicyNumber(), "Field UpdateInvestmentPolicyCommand.policyNumber should not be null" );
		Assert.notNull( investmentPolicy.getConstraints(), "Field UpdateInvestmentPolicyCommand.constraints should not be null" );
    }

	/**
	 * handles delete validation for a InvestmentPolicy
	 */
    public void validate( DeleteInvestmentPolicyCommand investmentPolicy ) throws Exception {
		Assert.notNull( investmentPolicy, "{commandAlias} should not be null" );
		Assert.notNull( investmentPolicy.getInvestmentPolicyId(), "DeleteInvestmentPolicyCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a InvestmentPolicy
	 */
	public void validate( InvestmentPolicyFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "InvestmentPolicyFetchOneSummary should not be null" );
		Assert.notNull( summary.getInvestmentPolicyId(), "InvestmentPolicyFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Portfolio validation for a InvestmentPolicy
	 * 
	 * @param	command AssignPortfolioToInvestmentPolicyCommand
	 */	
	public void validate( AssignPortfolioToInvestmentPolicyCommand command ) throws Exception {
		Assert.notNull( command, "AssignPortfolioToInvestmentPolicyCommand should not be null" );
		Assert.notNull( command.getInvestmentPolicyId(), "AssignPortfolioToInvestmentPolicyCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPortfolioToInvestmentPolicyCommand assignment should not be null" );
	}

	/**
	 * handles unassign Portfolio validation for a InvestmentPolicy
	 * 
	 * @param	command UnAssignPortfolioFromInvestmentPolicyCommand
	 */	
	public void validate( UnAssignPortfolioFromInvestmentPolicyCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPortfolioFromInvestmentPolicyCommand should not be null" );
		Assert.notNull( command.getInvestmentPolicyId(), "UnAssignPortfolioFromInvestmentPolicyCommand identifier should not be null" );
	}
	/**
	 * handles assign RiskAssessment validation for a InvestmentPolicy
	 * 
	 * @param	command AssignRiskAssessmentToInvestmentPolicyCommand
	 */	
	public void validate( AssignRiskAssessmentToInvestmentPolicyCommand command ) throws Exception {
		Assert.notNull( command, "AssignRiskAssessmentToInvestmentPolicyCommand should not be null" );
		Assert.notNull( command.getInvestmentPolicyId(), "AssignRiskAssessmentToInvestmentPolicyCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignRiskAssessmentToInvestmentPolicyCommand assignment should not be null" );
	}

	/**
	 * handles unassign RiskAssessment validation for a InvestmentPolicy
	 * 
	 * @param	command UnAssignRiskAssessmentFromInvestmentPolicyCommand
	 */	
	public void validate( UnAssignRiskAssessmentFromInvestmentPolicyCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignRiskAssessmentFromInvestmentPolicyCommand should not be null" );
		Assert.notNull( command.getInvestmentPolicyId(), "UnAssignRiskAssessmentFromInvestmentPolicyCommand identifier should not be null" );
	}

	/**
	 * handles add to Goals validation for a InvestmentPolicy
	 * 
	 * @param	command AssignGoalsToInvestmentPolicyCommand
	 */	
	public void validate( AssignGoalsToInvestmentPolicyCommand command ) throws Exception {
		Assert.notNull( command, "AssignGoalsToInvestmentPolicyCommand should not be null" );
		Assert.notNull( command.getInvestmentPolicyId(), "AssignGoalsToInvestmentPolicyCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignGoalsToInvestmentPolicyCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Goals validation for a InvestmentPolicy
	 * 
	 * @param	command RemoveGoalsFromInvestmentPolicyCommand
	 */	
	public void validate( RemoveGoalsFromInvestmentPolicyCommand command ) throws Exception {
		Assert.notNull( command, "RemoveGoalsFromInvestmentPolicyCommand should not be null" );
		Assert.notNull( command.getInvestmentPolicyId(), "RemoveGoalsFromInvestmentPolicyCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveGoalsFromInvestmentPolicyCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getWealthGoalId(), "RemoveGoalsFromInvestmentPolicyCommand removeFrom attribubte identifier should not be null" );
	}
	

}
