/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>MarketPriceValidation</h2>
 * <p>
 * The MarketPrice Validation  handles state validation of a MarketPrice include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateMarketPriceCommand</li>
 *      <li>UpdateMarketPriceCommand</li>
 *      <li>DeleteMarketPriceCommand</li>
 *set( false = false )
  *       <li>AssignSecurityToMarketPriceCommand</li>
 *       <li>UnAssignSecurityFromMarketPriceCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class MarketPriceValidator {
		
	/**
	 * default constructor
	 */
	protected MarketPriceValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public MarketPriceValidator getInstance() {
		return new MarketPriceValidator();
	}
		
	/**
	 * handles creation validation for a MarketPrice
	 */
	public void validate( CreateMarketPriceCommand marketPrice )throws Exception {
		Assert.notNull( marketPrice, "CreateMarketPriceCommand should not be null" );
//		Assert.isNull( marketPrice.getMarketPriceId(), "CreateMarketPriceCommand identifier should be null" );
		Assert.notNull( marketPrice.getPrice(), "Field CreateMarketPriceCommand.price should not be null" );
		Assert.notNull( marketPrice.getPriceDate(), "Field CreateMarketPriceCommand.priceDate should not be null" );
	}

	/**
	 * handles update validation for a MarketPrice
	 */
	public void validate( UpdateMarketPriceCommand marketPrice ) throws Exception {
		Assert.notNull( marketPrice, "UpdateMarketPriceCommand should not be null" );
		Assert.notNull( marketPrice.getMarketPriceId(), "UpdateMarketPriceCommand identifier should not be null" );
		Assert.notNull( marketPrice.getPrice(), "Field UpdateMarketPriceCommand.price should not be null" );
		Assert.notNull( marketPrice.getPriceDate(), "Field UpdateMarketPriceCommand.priceDate should not be null" );
    }

	/**
	 * handles delete validation for a MarketPrice
	 */
    public void validate( DeleteMarketPriceCommand marketPrice ) throws Exception {
		Assert.notNull( marketPrice, "{commandAlias} should not be null" );
		Assert.notNull( marketPrice.getMarketPriceId(), "DeleteMarketPriceCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a MarketPrice
	 */
	public void validate( MarketPriceFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "MarketPriceFetchOneSummary should not be null" );
		Assert.notNull( summary.getMarketPriceId(), "MarketPriceFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Security validation for a MarketPrice
	 * 
	 * @param	command AssignSecurityToMarketPriceCommand
	 */	
	public void validate( AssignSecurityToMarketPriceCommand command ) throws Exception {
		Assert.notNull( command, "AssignSecurityToMarketPriceCommand should not be null" );
		Assert.notNull( command.getMarketPriceId(), "AssignSecurityToMarketPriceCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignSecurityToMarketPriceCommand assignment should not be null" );
	}

	/**
	 * handles unassign Security validation for a MarketPrice
	 * 
	 * @param	command UnAssignSecurityFromMarketPriceCommand
	 */	
	public void validate( UnAssignSecurityFromMarketPriceCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignSecurityFromMarketPriceCommand should not be null" );
		Assert.notNull( command.getMarketPriceId(), "UnAssignSecurityFromMarketPriceCommand identifier should not be null" );
	}


}
