/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>OfficeValidation</h2>
 * <p>
 * The Office Validation  handles state validation of a Office include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateOfficeCommand</li>
 *      <li>UpdateOfficeCommand</li>
 *      <li>DeleteOfficeCommand</li>
 *set( false = false )
  *       <li>AssignFirmToOfficeCommand</li>
 *       <li>UnAssignFirmFromOfficeCommand</li>
   *       <li>AssignAdvisorsToOfficeCommand</li>
 *       <li>RemoveAdvisorsFromOfficeCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class OfficeValidator {
		
	/**
	 * default constructor
	 */
	protected OfficeValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public OfficeValidator getInstance() {
		return new OfficeValidator();
	}
		
	/**
	 * handles creation validation for a Office
	 */
	public void validate( CreateOfficeCommand office )throws Exception {
		Assert.notNull( office, "CreateOfficeCommand should not be null" );
//		Assert.isNull( office.getOfficeId(), "CreateOfficeCommand identifier should be null" );
		Assert.notNull( office.getName(), "Field CreateOfficeCommand.name should not be null" );
		Assert.notNull( office.getAddress(), "Field CreateOfficeCommand.address should not be null" );
	}

	/**
	 * handles update validation for a Office
	 */
	public void validate( UpdateOfficeCommand office ) throws Exception {
		Assert.notNull( office, "UpdateOfficeCommand should not be null" );
		Assert.notNull( office.getOfficeId(), "UpdateOfficeCommand identifier should not be null" );
		Assert.notNull( office.getName(), "Field UpdateOfficeCommand.name should not be null" );
		Assert.notNull( office.getAddress(), "Field UpdateOfficeCommand.address should not be null" );
    }

	/**
	 * handles delete validation for a Office
	 */
    public void validate( DeleteOfficeCommand office ) throws Exception {
		Assert.notNull( office, "{commandAlias} should not be null" );
		Assert.notNull( office.getOfficeId(), "DeleteOfficeCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Office
	 */
	public void validate( OfficeFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "OfficeFetchOneSummary should not be null" );
		Assert.notNull( summary.getOfficeId(), "OfficeFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Firm validation for a Office
	 * 
	 * @param	command AssignFirmToOfficeCommand
	 */	
	public void validate( AssignFirmToOfficeCommand command ) throws Exception {
		Assert.notNull( command, "AssignFirmToOfficeCommand should not be null" );
		Assert.notNull( command.getOfficeId(), "AssignFirmToOfficeCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignFirmToOfficeCommand assignment should not be null" );
	}

	/**
	 * handles unassign Firm validation for a Office
	 * 
	 * @param	command UnAssignFirmFromOfficeCommand
	 */	
	public void validate( UnAssignFirmFromOfficeCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignFirmFromOfficeCommand should not be null" );
		Assert.notNull( command.getOfficeId(), "UnAssignFirmFromOfficeCommand identifier should not be null" );
	}

	/**
	 * handles add to Advisors validation for a Office
	 * 
	 * @param	command AssignAdvisorsToOfficeCommand
	 */	
	public void validate( AssignAdvisorsToOfficeCommand command ) throws Exception {
		Assert.notNull( command, "AssignAdvisorsToOfficeCommand should not be null" );
		Assert.notNull( command.getOfficeId(), "AssignAdvisorsToOfficeCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAdvisorsToOfficeCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Advisors validation for a Office
	 * 
	 * @param	command RemoveAdvisorsFromOfficeCommand
	 */	
	public void validate( RemoveAdvisorsFromOfficeCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAdvisorsFromOfficeCommand should not be null" );
		Assert.notNull( command.getOfficeId(), "RemoveAdvisorsFromOfficeCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAdvisorsFromOfficeCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getAdvisorId(), "RemoveAdvisorsFromOfficeCommand removeFrom attribubte identifier should not be null" );
	}
	

}
