/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>OrderValidation</h2>
 * <p>
 * The Order Validation  handles state validation of a Order include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateOrderCommand</li>
 *      <li>UpdateOrderCommand</li>
 *      <li>DeleteOrderCommand</li>
 *set( false = false )
  *       <li>AssignAccountToOrderCommand</li>
 *       <li>UnAssignAccountFromOrderCommand</li>
  *       <li>AssignSecurityToOrderCommand</li>
 *       <li>UnAssignSecurityFromOrderCommand</li>
  *       <li>AssignAdvisorToOrderCommand</li>
 *       <li>UnAssignAdvisorFromOrderCommand</li>
   *       <li>AssignAllocationsToOrderCommand</li>
 *       <li>RemoveAllocationsFromOrderCommand</li>
 *   </ul>
 *
  *       <li>AssignTradesToOrderCommand</li>
 *       <li>RemoveTradesFromOrderCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class OrderValidator {
		
	/**
	 * default constructor
	 */
	protected OrderValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public OrderValidator getInstance() {
		return new OrderValidator();
	}
		
	/**
	 * handles creation validation for a Order
	 */
	public void validate( CreateOrderCommand order )throws Exception {
		Assert.notNull( order, "CreateOrderCommand should not be null" );
//		Assert.isNull( order.getOrderId(), "CreateOrderCommand identifier should be null" );
		Assert.notNull( order.getOrderNumber(), "Field CreateOrderCommand.orderNumber should not be null" );
		Assert.notNull( order.getQuantity(), "Field CreateOrderCommand.quantity should not be null" );
		Assert.notNull( order.getLimitPrice(), "Field CreateOrderCommand.limitPrice should not be null" );
	}

	/**
	 * handles update validation for a Order
	 */
	public void validate( UpdateOrderCommand order ) throws Exception {
		Assert.notNull( order, "UpdateOrderCommand should not be null" );
		Assert.notNull( order.getOrderId(), "UpdateOrderCommand identifier should not be null" );
		Assert.notNull( order.getOrderNumber(), "Field UpdateOrderCommand.orderNumber should not be null" );
		Assert.notNull( order.getQuantity(), "Field UpdateOrderCommand.quantity should not be null" );
		Assert.notNull( order.getLimitPrice(), "Field UpdateOrderCommand.limitPrice should not be null" );
    }

	/**
	 * handles delete validation for a Order
	 */
    public void validate( DeleteOrderCommand order ) throws Exception {
		Assert.notNull( order, "{commandAlias} should not be null" );
		Assert.notNull( order.getOrderId(), "DeleteOrderCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Order
	 */
	public void validate( OrderFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "OrderFetchOneSummary should not be null" );
		Assert.notNull( summary.getOrderId(), "OrderFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Account validation for a Order
	 * 
	 * @param	command AssignAccountToOrderCommand
	 */	
	public void validate( AssignAccountToOrderCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "AssignAccountToOrderCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToOrderCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a Order
	 * 
	 * @param	command UnAssignAccountFromOrderCommand
	 */	
	public void validate( UnAssignAccountFromOrderCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "UnAssignAccountFromOrderCommand identifier should not be null" );
	}
	/**
	 * handles assign Security validation for a Order
	 * 
	 * @param	command AssignSecurityToOrderCommand
	 */	
	public void validate( AssignSecurityToOrderCommand command ) throws Exception {
		Assert.notNull( command, "AssignSecurityToOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "AssignSecurityToOrderCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignSecurityToOrderCommand assignment should not be null" );
	}

	/**
	 * handles unassign Security validation for a Order
	 * 
	 * @param	command UnAssignSecurityFromOrderCommand
	 */	
	public void validate( UnAssignSecurityFromOrderCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignSecurityFromOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "UnAssignSecurityFromOrderCommand identifier should not be null" );
	}
	/**
	 * handles assign Advisor validation for a Order
	 * 
	 * @param	command AssignAdvisorToOrderCommand
	 */	
	public void validate( AssignAdvisorToOrderCommand command ) throws Exception {
		Assert.notNull( command, "AssignAdvisorToOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "AssignAdvisorToOrderCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAdvisorToOrderCommand assignment should not be null" );
	}

	/**
	 * handles unassign Advisor validation for a Order
	 * 
	 * @param	command UnAssignAdvisorFromOrderCommand
	 */	
	public void validate( UnAssignAdvisorFromOrderCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAdvisorFromOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "UnAssignAdvisorFromOrderCommand identifier should not be null" );
	}

	/**
	 * handles add to Allocations validation for a Order
	 * 
	 * @param	command AssignAllocationsToOrderCommand
	 */	
	public void validate( AssignAllocationsToOrderCommand command ) throws Exception {
		Assert.notNull( command, "AssignAllocationsToOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "AssignAllocationsToOrderCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignAllocationsToOrderCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Allocations validation for a Order
	 * 
	 * @param	command RemoveAllocationsFromOrderCommand
	 */	
	public void validate( RemoveAllocationsFromOrderCommand command ) throws Exception {
		Assert.notNull( command, "RemoveAllocationsFromOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "RemoveAllocationsFromOrderCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveAllocationsFromOrderCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getOrderAllocationId(), "RemoveAllocationsFromOrderCommand removeFrom attribubte identifier should not be null" );
	}
	
	/**
	 * handles add to Trades validation for a Order
	 * 
	 * @param	command AssignTradesToOrderCommand
	 */	
	public void validate( AssignTradesToOrderCommand command ) throws Exception {
		Assert.notNull( command, "AssignTradesToOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "AssignTradesToOrderCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignTradesToOrderCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from Trades validation for a Order
	 * 
	 * @param	command RemoveTradesFromOrderCommand
	 */	
	public void validate( RemoveTradesFromOrderCommand command ) throws Exception {
		Assert.notNull( command, "RemoveTradesFromOrderCommand should not be null" );
		Assert.notNull( command.getOrderId(), "RemoveTradesFromOrderCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveTradesFromOrderCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getTradeId(), "RemoveTradesFromOrderCommand removeFrom attribubte identifier should not be null" );
	}
	

}
