/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>ProposalValidation</h2>
 * <p>
 * The Proposal Validation  handles state validation of a Proposal include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateProposalCommand</li>
 *      <li>UpdateProposalCommand</li>
 *      <li>DeleteProposalCommand</li>
 *set( false = false )
  *       <li>AssignHouseholdToProposalCommand</li>
 *       <li>UnAssignHouseholdFromProposalCommand</li>
  *       <li>AssignAdvisorToProposalCommand</li>
 *       <li>UnAssignAdvisorFromProposalCommand</li>
  *       <li>AssignModelPortfolioToProposalCommand</li>
 *       <li>UnAssignModelPortfolioFromProposalCommand</li>
  *       <li>AssignAccountToProposalCommand</li>
 *       <li>UnAssignAccountFromProposalCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class ProposalValidator {
		
	/**
	 * default constructor
	 */
	protected ProposalValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public ProposalValidator getInstance() {
		return new ProposalValidator();
	}
		
	/**
	 * handles creation validation for a Proposal
	 */
	public void validate( CreateProposalCommand proposal )throws Exception {
		Assert.notNull( proposal, "CreateProposalCommand should not be null" );
//		Assert.isNull( proposal.getProposalId(), "CreateProposalCommand identifier should be null" );
		Assert.notNull( proposal.getProposalNumber(), "Field CreateProposalCommand.proposalNumber should not be null" );
		Assert.notNull( proposal.getCreatedDate(), "Field CreateProposalCommand.createdDate should not be null" );
		Assert.notNull( proposal.getRecommendationText(), "Field CreateProposalCommand.recommendationText should not be null" );
	}

	/**
	 * handles update validation for a Proposal
	 */
	public void validate( UpdateProposalCommand proposal ) throws Exception {
		Assert.notNull( proposal, "UpdateProposalCommand should not be null" );
		Assert.notNull( proposal.getProposalId(), "UpdateProposalCommand identifier should not be null" );
		Assert.notNull( proposal.getProposalNumber(), "Field UpdateProposalCommand.proposalNumber should not be null" );
		Assert.notNull( proposal.getCreatedDate(), "Field UpdateProposalCommand.createdDate should not be null" );
		Assert.notNull( proposal.getRecommendationText(), "Field UpdateProposalCommand.recommendationText should not be null" );
    }

	/**
	 * handles delete validation for a Proposal
	 */
    public void validate( DeleteProposalCommand proposal ) throws Exception {
		Assert.notNull( proposal, "{commandAlias} should not be null" );
		Assert.notNull( proposal.getProposalId(), "DeleteProposalCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a Proposal
	 */
	public void validate( ProposalFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "ProposalFetchOneSummary should not be null" );
		Assert.notNull( summary.getProposalId(), "ProposalFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Household validation for a Proposal
	 * 
	 * @param	command AssignHouseholdToProposalCommand
	 */	
	public void validate( AssignHouseholdToProposalCommand command ) throws Exception {
		Assert.notNull( command, "AssignHouseholdToProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "AssignHouseholdToProposalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignHouseholdToProposalCommand assignment should not be null" );
	}

	/**
	 * handles unassign Household validation for a Proposal
	 * 
	 * @param	command UnAssignHouseholdFromProposalCommand
	 */	
	public void validate( UnAssignHouseholdFromProposalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignHouseholdFromProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "UnAssignHouseholdFromProposalCommand identifier should not be null" );
	}
	/**
	 * handles assign Advisor validation for a Proposal
	 * 
	 * @param	command AssignAdvisorToProposalCommand
	 */	
	public void validate( AssignAdvisorToProposalCommand command ) throws Exception {
		Assert.notNull( command, "AssignAdvisorToProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "AssignAdvisorToProposalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAdvisorToProposalCommand assignment should not be null" );
	}

	/**
	 * handles unassign Advisor validation for a Proposal
	 * 
	 * @param	command UnAssignAdvisorFromProposalCommand
	 */	
	public void validate( UnAssignAdvisorFromProposalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAdvisorFromProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "UnAssignAdvisorFromProposalCommand identifier should not be null" );
	}
	/**
	 * handles assign ModelPortfolio validation for a Proposal
	 * 
	 * @param	command AssignModelPortfolioToProposalCommand
	 */	
	public void validate( AssignModelPortfolioToProposalCommand command ) throws Exception {
		Assert.notNull( command, "AssignModelPortfolioToProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "AssignModelPortfolioToProposalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignModelPortfolioToProposalCommand assignment should not be null" );
	}

	/**
	 * handles unassign ModelPortfolio validation for a Proposal
	 * 
	 * @param	command UnAssignModelPortfolioFromProposalCommand
	 */	
	public void validate( UnAssignModelPortfolioFromProposalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignModelPortfolioFromProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "UnAssignModelPortfolioFromProposalCommand identifier should not be null" );
	}
	/**
	 * handles assign Account validation for a Proposal
	 * 
	 * @param	command AssignAccountToProposalCommand
	 */	
	public void validate( AssignAccountToProposalCommand command ) throws Exception {
		Assert.notNull( command, "AssignAccountToProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "AssignAccountToProposalCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAccountToProposalCommand assignment should not be null" );
	}

	/**
	 * handles unassign Account validation for a Proposal
	 * 
	 * @param	command UnAssignAccountFromProposalCommand
	 */	
	public void validate( UnAssignAccountFromProposalCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAccountFromProposalCommand should not be null" );
		Assert.notNull( command.getProposalId(), "UnAssignAccountFromProposalCommand identifier should not be null" );
	}


}
