/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>RebalancePlanValidation</h2>
 * <p>
 * The RebalancePlan Validation  handles state validation of a RebalancePlan include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateRebalancePlanCommand</li>
 *      <li>UpdateRebalancePlanCommand</li>
 *      <li>DeleteRebalancePlanCommand</li>
 *set( false = false )
  *       <li>AssignPortfolioToRebalancePlanCommand</li>
 *       <li>UnAssignPortfolioFromRebalancePlanCommand</li>
  *       <li>AssignAdvisorToRebalancePlanCommand</li>
 *       <li>UnAssignAdvisorFromRebalancePlanCommand</li>
   *       <li>AssignProposedOrdersToRebalancePlanCommand</li>
 *       <li>RemoveProposedOrdersFromRebalancePlanCommand</li>
 *   </ul>
 *
  * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class RebalancePlanValidator {
		
	/**
	 * default constructor
	 */
	protected RebalancePlanValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public RebalancePlanValidator getInstance() {
		return new RebalancePlanValidator();
	}
		
	/**
	 * handles creation validation for a RebalancePlan
	 */
	public void validate( CreateRebalancePlanCommand rebalancePlan )throws Exception {
		Assert.notNull( rebalancePlan, "CreateRebalancePlanCommand should not be null" );
//		Assert.isNull( rebalancePlan.getRebalancePlanId(), "CreateRebalancePlanCommand identifier should be null" );
		Assert.notNull( rebalancePlan.getPlanDate(), "Field CreateRebalancePlanCommand.planDate should not be null" );
	}

	/**
	 * handles update validation for a RebalancePlan
	 */
	public void validate( UpdateRebalancePlanCommand rebalancePlan ) throws Exception {
		Assert.notNull( rebalancePlan, "UpdateRebalancePlanCommand should not be null" );
		Assert.notNull( rebalancePlan.getRebalancePlanId(), "UpdateRebalancePlanCommand identifier should not be null" );
		Assert.notNull( rebalancePlan.getPlanDate(), "Field UpdateRebalancePlanCommand.planDate should not be null" );
    }

	/**
	 * handles delete validation for a RebalancePlan
	 */
    public void validate( DeleteRebalancePlanCommand rebalancePlan ) throws Exception {
		Assert.notNull( rebalancePlan, "{commandAlias} should not be null" );
		Assert.notNull( rebalancePlan.getRebalancePlanId(), "DeleteRebalancePlanCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a RebalancePlan
	 */
	public void validate( RebalancePlanFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "RebalancePlanFetchOneSummary should not be null" );
		Assert.notNull( summary.getRebalancePlanId(), "RebalancePlanFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Portfolio validation for a RebalancePlan
	 * 
	 * @param	command AssignPortfolioToRebalancePlanCommand
	 */	
	public void validate( AssignPortfolioToRebalancePlanCommand command ) throws Exception {
		Assert.notNull( command, "AssignPortfolioToRebalancePlanCommand should not be null" );
		Assert.notNull( command.getRebalancePlanId(), "AssignPortfolioToRebalancePlanCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPortfolioToRebalancePlanCommand assignment should not be null" );
	}

	/**
	 * handles unassign Portfolio validation for a RebalancePlan
	 * 
	 * @param	command UnAssignPortfolioFromRebalancePlanCommand
	 */	
	public void validate( UnAssignPortfolioFromRebalancePlanCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPortfolioFromRebalancePlanCommand should not be null" );
		Assert.notNull( command.getRebalancePlanId(), "UnAssignPortfolioFromRebalancePlanCommand identifier should not be null" );
	}
	/**
	 * handles assign Advisor validation for a RebalancePlan
	 * 
	 * @param	command AssignAdvisorToRebalancePlanCommand
	 */	
	public void validate( AssignAdvisorToRebalancePlanCommand command ) throws Exception {
		Assert.notNull( command, "AssignAdvisorToRebalancePlanCommand should not be null" );
		Assert.notNull( command.getRebalancePlanId(), "AssignAdvisorToRebalancePlanCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignAdvisorToRebalancePlanCommand assignment should not be null" );
	}

	/**
	 * handles unassign Advisor validation for a RebalancePlan
	 * 
	 * @param	command UnAssignAdvisorFromRebalancePlanCommand
	 */	
	public void validate( UnAssignAdvisorFromRebalancePlanCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignAdvisorFromRebalancePlanCommand should not be null" );
		Assert.notNull( command.getRebalancePlanId(), "UnAssignAdvisorFromRebalancePlanCommand identifier should not be null" );
	}

	/**
	 * handles add to ProposedOrders validation for a RebalancePlan
	 * 
	 * @param	command AssignProposedOrdersToRebalancePlanCommand
	 */	
	public void validate( AssignProposedOrdersToRebalancePlanCommand command ) throws Exception {
		Assert.notNull( command, "AssignProposedOrdersToRebalancePlanCommand should not be null" );
		Assert.notNull( command.getRebalancePlanId(), "AssignProposedOrdersToRebalancePlanCommand identifier should not be null" );
		Assert.notNull( command.getAddTo(), "AssignProposedOrdersToRebalancePlanCommand addTo attribute should not be null" );
	}

	/**
	 * handles remove from ProposedOrders validation for a RebalancePlan
	 * 
	 * @param	command RemoveProposedOrdersFromRebalancePlanCommand
	 */	
	public void validate( RemoveProposedOrdersFromRebalancePlanCommand command ) throws Exception {
		Assert.notNull( command, "RemoveProposedOrdersFromRebalancePlanCommand should not be null" );
		Assert.notNull( command.getRebalancePlanId(), "RemoveProposedOrdersFromRebalancePlanCommand identifier should not be null" );
		Assert.notNull( command.getRemoveFrom(), "RemoveProposedOrdersFromRebalancePlanCommand removeFrom attribute should not be null" );
		Assert.notNull( command.getRemoveFrom().getOrderId(), "RemoveProposedOrdersFromRebalancePlanCommand removeFrom attribubte identifier should not be null" );
	}
	

}
