/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.validator;

import org.springframework.util.Assert;

import com.harbormaster.api.*;

/**
 * <h2>TaxLotValidation</h2>
 * <p>
 * The TaxLot Validation  handles state validation of a TaxLot include direct attributes and single/multiple associations.
 * </p>
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Commands Validated</h3>
 *      <ul>
 *      <li>CreateTaxLotCommand</li>
 *      <li>UpdateTaxLotCommand</li>
 *      <li>DeleteTaxLotCommand</li>
 *set( false = false )
  *       <li>AssignPositionToTaxLotCommand</li>
 *       <li>UnAssignPositionFromTaxLotCommand</li>
   * <p>
 * @author Harbormaster Dev Team
 * </p>
 */
public class TaxLotValidator {
		
	/**
	 * default constructor
	 */
	protected TaxLotValidator() {	
	}
	
	/**
	 * factory method
	 */
	static public TaxLotValidator getInstance() {
		return new TaxLotValidator();
	}
		
	/**
	 * handles creation validation for a TaxLot
	 */
	public void validate( CreateTaxLotCommand taxLot )throws Exception {
		Assert.notNull( taxLot, "CreateTaxLotCommand should not be null" );
//		Assert.isNull( taxLot.getTaxLotId(), "CreateTaxLotCommand identifier should be null" );
		Assert.notNull( taxLot.getAcquisitionDate(), "Field CreateTaxLotCommand.acquisitionDate should not be null" );
		Assert.notNull( taxLot.getQuantity(), "Field CreateTaxLotCommand.quantity should not be null" );
		Assert.notNull( taxLot.getUnitCost(), "Field CreateTaxLotCommand.unitCost should not be null" );
	}

	/**
	 * handles update validation for a TaxLot
	 */
	public void validate( UpdateTaxLotCommand taxLot ) throws Exception {
		Assert.notNull( taxLot, "UpdateTaxLotCommand should not be null" );
		Assert.notNull( taxLot.getTaxLotId(), "UpdateTaxLotCommand identifier should not be null" );
		Assert.notNull( taxLot.getAcquisitionDate(), "Field UpdateTaxLotCommand.acquisitionDate should not be null" );
		Assert.notNull( taxLot.getQuantity(), "Field UpdateTaxLotCommand.quantity should not be null" );
		Assert.notNull( taxLot.getUnitCost(), "Field UpdateTaxLotCommand.unitCost should not be null" );
    }

	/**
	 * handles delete validation for a TaxLot
	 */
    public void validate( DeleteTaxLotCommand taxLot ) throws Exception {
		Assert.notNull( taxLot, "{commandAlias} should not be null" );
		Assert.notNull( taxLot.getTaxLotId(), "DeleteTaxLotCommand identifier should not be null" );
	}
	
	/**
	 * handles fetchOne validation for a TaxLot
	 */
	public void validate( TaxLotFetchOneSummary summary ) throws Exception {
		Assert.notNull( summary, "TaxLotFetchOneSummary should not be null" );
		Assert.notNull( summary.getTaxLotId(), "TaxLotFetchOneSummary identifier should not be null" );
	}

	/**
	 * handles assign Position validation for a TaxLot
	 * 
	 * @param	command AssignPositionToTaxLotCommand
	 */	
	public void validate( AssignPositionToTaxLotCommand command ) throws Exception {
		Assert.notNull( command, "AssignPositionToTaxLotCommand should not be null" );
		Assert.notNull( command.getTaxLotId(), "AssignPositionToTaxLotCommand identifier should not be null" );
		Assert.notNull( command.getAssignment(), "AssignPositionToTaxLotCommand assignment should not be null" );
	}

	/**
	 * handles unassign Position validation for a TaxLot
	 * 
	 * @param	command UnAssignPositionFromTaxLotCommand
	 */	
	public void validate( UnAssignPositionFromTaxLotCommand command ) throws Exception {
		Assert.notNull( command, "UnAssignPositionFromTaxLotCommand should not be null" );
		Assert.notNull( command.getTaxLotId(), "UnAssignPositionFromTaxLotCommand identifier should not be null" );
	}


}
