/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * AssetAllocationSliceRestController as REST API
 *
 * <p>Exposes REST endpoints for the AssetAllocationSlice entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	AssetAllocationSliceBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateAssetAllocationSliceCommand</li>
 *      <li></li>UpdateAssetAllocationSliceCommand</li>
 *      <liDeleteAssetAllocationSliceCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/AssetAllocationSlice")
public class AssetAllocationSliceRestController extends BaseSpringRestController {

    /**
     * Handles create a AssetAllocationSlice.  if not key provided, calls create, otherwise calls save
     * @param		AssetAllocationSlice	assetAllocationSlice
     * @return		AssetAllocationSlice 
     */
	@PostMapping("/create")
    public AssetAllocationSlice create( @RequestBody(required=true) CreateAssetAllocationSliceCommand command ) {
    	AssetAllocationSlice entity = null;
		try {       
        	
			entity = AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance().createAssetAllocationSlice( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a AssetAllocationSlice.  if no key provided, calls create, otherwise calls save
     * @param		AssetAllocationSlice assetAllocationSlice
     * @return		AssetAllocationSlice
     */
	@PutMapping("/update")
    public AssetAllocationSlice update( @RequestBody(required=true) UpdateAssetAllocationSliceCommand command ) {
		AssetAllocationSlice entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateAssetAllocationSliceCommand
			// -----------------------------------------------
			entity = AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance().updateAssetAllocationSlice(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "AssetAllocationSliceController:update() - successfully update AssetAllocationSlice - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a AssetAllocationSlice entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteAssetAllocationSliceCommand command ) {                
    	try {
        	AssetAllocationSliceBusinessDelegate delegate = AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted AssetAllocationSlice with key " + command.getAssetAllocationSliceId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a AssetAllocationSlice using a UUID
     * @param		UUID uuid 
     * @return		AssetAllocationSlice
     */    
    @GetMapping("/load")
    public AssetAllocationSlice load( @RequestParam(required=true) UUID uuid ) {    	
    	AssetAllocationSlice entity = null;

    	try {  
    		entity = AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance().getAssetAllocationSlice( new AssetAllocationSliceFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load AssetAllocationSlice using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all AssetAllocationSlice business objects
     * @return		Set<AssetAllocationSlice>
     */
    @GetMapping("/")
    public List<AssetAllocationSlice> loadAll() {                
    	List<AssetAllocationSlice> assetAllocationSliceList = null;
        
    	try {
            // load the AssetAllocationSlice
            assetAllocationSliceList = AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance().getAllAssetAllocationSlice();
            
            if ( assetAllocationSliceList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all AssetAllocationSlices" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all AssetAllocationSlices ", exc );
        	return null;
        }

        return assetAllocationSliceList;
                            
    }

    /**
     * save ModelPortfolio on AssetAllocationSlice
     * @param		command AssignModelPortfolioToAssetAllocationSliceCommand
     */     
	@PutMapping("/assignModelPortfolio")
	public void assignModelPortfolio( @RequestBody AssignModelPortfolioToAssetAllocationSliceCommand command ) {
		try {
			AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance().assignModelPortfolio( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign ModelPortfolio", exc );
        }
	}

    /**
     * unassign ModelPortfolio on AssetAllocationSlice
     * @param		 command UnAssignModelPortfolioFromAssetAllocationSliceCommand
     */     
	@PutMapping("/unAssignModelPortfolio")
	public void unAssignModelPortfolio( @RequestBody(required=true)  UnAssignModelPortfolioFromAssetAllocationSliceCommand command ) {
		try {
			AssetAllocationSliceBusinessDelegate.getAssetAllocationSliceInstance().unAssignModelPortfolio( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign ModelPortfolio", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected AssetAllocationSlice assetAllocationSlice = null;
    private static final Logger LOGGER = Logger.getLogger(AssetAllocationSliceRestController.class.getName());
    
}
