/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * BillingRunRestController as REST API
 *
 * <p>Exposes REST endpoints for the BillingRun entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	BillingRunService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateBillingRunCommand</li>
 *      <li></li>UpdateBillingRunCommand</li>
 *      <liDeleteBillingRunCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/BillingRun")
public class BillingRunRestController extends BaseSpringRestController {

	public BillingRunRestController( BillingRunService service ) {
		this.service = service;
	}
    /**
     * Handles create a BillingRun.  if not key provided, calls create, otherwise calls save
     * @param		BillingRun	billingRun
     * @return		BillingRun 
     */
	@PostMapping("/create")
    public BillingRun create( @RequestBody(required=true) CreateBillingRunCommand command ) {
    	BillingRun entity = null;
		try {       
        	
			entity = service.createBillingRun( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a BillingRun.  if no key provided, calls create, otherwise calls save
     * @param		BillingRun billingRun
     * @return		BillingRun
     */
	@PutMapping("/update")
    public BillingRun update( @RequestBody(required=true) UpdateBillingRunCommand command ) {
		BillingRun entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateBillingRunCommand
			// -----------------------------------------------
			entity = service.updateBillingRun(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "BillingRunController:update() - successfully update BillingRun - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a BillingRun entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteBillingRunCommand command ) {                
    	try {
        	BillingRunService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted BillingRun with key " + command.getBillingRunId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a BillingRun using a UUID
     * @param		UUID uuid 
     * @return		BillingRun
     */    
    @GetMapping("/load")
    public BillingRun load( @RequestParam(required=true) UUID uuid ) {    	
    	BillingRun entity = null;

    	try {  
    		entity = service.getBillingRun( new BillingRunFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load BillingRun using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all BillingRun business objects
     * @return		Set<BillingRun>
     */
    @GetMapping("/")
    public List<BillingRun> loadAll() {                
    	List<BillingRun> billingRunList = null;
        
    	try {
            // load the BillingRun
            billingRunList = service.getAllBillingRun();
            
            if ( billingRunList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all BillingRuns" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all BillingRuns ", exc );
        	return null;
        }

        return billingRunList;
                            
    }

    /**
     * save FeeSchedule on BillingRun
     * @param		command AssignFeeScheduleToBillingRunCommand
     */     
	@PutMapping("/assignFeeSchedule")
	public void assignFeeSchedule( @RequestBody AssignFeeScheduleToBillingRunCommand command ) {
		try {
			service.assignFeeSchedule( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign FeeSchedule", exc );
        }
	}

    /**
     * unassign FeeSchedule on BillingRun
     * @param		 command UnAssignFeeScheduleFromBillingRunCommand
     */     
	@PutMapping("/unAssignFeeSchedule")
	public void unAssignFeeSchedule( @RequestBody(required=true)  UnAssignFeeScheduleFromBillingRunCommand command ) {
		try {
			service.unAssignFeeSchedule( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign FeeSchedule", exc );
		}
	}
	

    /**
     * save Invoices on BillingRun
     * @param		command AssignInvoicesToBillingRunCommand
     */     
	@PutMapping("/addToInvoices")
	public void addToInvoices( @RequestBody(required=true) AssignInvoicesToBillingRunCommand command ) {
		try {
			service.addToInvoices( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Invoices", exc );
		}
	}

    /**
     * remove Invoices on BillingRun
     * @param		command RemoveInvoicesFromBillingRunCommand
     */     	
	@PutMapping("/removeFromInvoices")
	public void removeFromInvoices( 	@RequestBody(required=true) RemoveInvoicesFromBillingRunCommand command )
	{		
		try {
			service.removeFromInvoices( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Invoices", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected BillingRun billingRun = null;
	protected BillingRunService service = null;
    private static final Logger LOGGER = Logger.getLogger(BillingRunRestController.class.getName());
    
}
