/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone National Bank Confidential
 *
 * 2026 Turnstone National Bank
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone National Bank - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CustodianRestController as REST API
 *
 * <p>Exposes REST endpoints for the Custodian entity.</p>
 *
 #generatedFrom()
 *
 * <h3>Services Used</h3>
 *
 *  	CustodianService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCustodianCommand</li>
 *      <li></li>UpdateCustodianCommand</li>
 *      <liDeleteCustodianCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Custodian")
public class CustodianRestController extends BaseSpringRestController {

	public CustodianRestController( CustodianService service ) {
		this.service = service;
	}
    /**
     * Handles create a Custodian.  if not key provided, calls create, otherwise calls save
     * @param		Custodian	custodian
     * @return		Custodian 
     */
	@PostMapping("/create")
    public Custodian create( @RequestBody(required=true) CreateCustodianCommand command ) {
    	Custodian entity = null;

		entity = service.createCustodian( command );
		LOGGER.info( "Successfully created Custodian with Id " + entity.getCustodianId()  );

		return entity;
    }

    /**
     * Handles updating a Custodian.  if no key provided, calls create, otherwise calls save
     * @param		Custodian custodian
     * @return		Custodian
     */
	@PutMapping("/update")
    public Custodian update( @RequestBody(required=true) UpdateCustodianCommand command ) {
		Custodian entity = null;

		entity = service.updateCustodian(command);
		LOGGER.info( "Successfully updated Custodian with Id " + command.getCustodianId()  );

		return entity;
	}
 
    /**
     * Handles deleting a Custodian entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCustodianCommand command ) {                
		service.delete( command );
		LOGGER.info( "Successfully deleted Custodian with Id " + command.getCustodianId()  );
	}
	
    /**
     * Handles loading a Custodian using a UUID
     * @param		UUID uuid 
     * @return		Custodian
     */    
    @GetMapping("/load")
    public Custodian load( @RequestParam(required=true) UUID uuid ) {
    	Custodian entity = service.getCustodian( new CustodianFetchOneSummary( uuid ) );

		LOGGER.info( "Successfully loaded Custodian with Id " + uuid   );

        return entity;
    }

    /**
     * Handles loading all Custodian business objects
     * @return		Set<Custodian>
     */
    @GetMapping("/")
    public List<Custodian> loadAll() {                
    	List<Custodian> custodianList = null;

		custodianList = service.getAllCustodian();
		LOGGER.info( "successfully loaded all Custodians" );

        return custodianList;
                            
    }


    /**
     * save Accounts on Custodian
     * @param		command AssignAccountsToCustodianCommand
     */     
	@PutMapping("/addToAccounts")
	public void addToAccounts( @RequestBody(required=true) AssignAccountsToCustodianCommand command ) {
		service.addToAccounts( command );
		LOGGER.info( "Successfully added Accounts with Id " + command.getCustodianId()  );
	}

    /**
     * remove Accounts on Custodian
     * @param		command RemoveAccountsFromCustodianCommand
     */     	
	@PutMapping("/removeFromAccounts")
	public void removeFromAccounts( 	@RequestBody(required=true) RemoveAccountsFromCustodianCommand command )
	{		
		service.removeFromAccounts( command );
		LOGGER.info( "Successfully removed Accounts with Id " + command.getCustodianId()  );
	}

    /**
     * save Transfers on Custodian
     * @param		command AssignTransfersToCustodianCommand
     */     
	@PutMapping("/addToTransfers")
	public void addToTransfers( @RequestBody(required=true) AssignTransfersToCustodianCommand command ) {
		service.addToTransfers( command );
		LOGGER.info( "Successfully added Transfers with Id " + command.getCustodianId()  );
	}

    /**
     * remove Transfers on Custodian
     * @param		command RemoveTransfersFromCustodianCommand
     */     	
	@PutMapping("/removeFromTransfers")
	public void removeFromTransfers( 	@RequestBody(required=true) RemoveTransfersFromCustodianCommand command )
	{		
		service.removeFromTransfers( command );
		LOGGER.info( "Successfully removed Transfers with Id " + command.getCustodianId()  );
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Custodian custodian = null;
	protected CustodianService service = null;
    private static final Logger LOGGER = LoggerFactory.getLogger(CustodianRestController.class.getName());
    
}
