/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CustodianRestController as REST API
 *
 * <p>Exposes REST endpoints for the Custodian entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CustodianBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCustodianCommand</li>
 *      <li></li>UpdateCustodianCommand</li>
 *      <liDeleteCustodianCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Custodian")
public class CustodianRestController extends BaseSpringRestController {

    /**
     * Handles create a Custodian.  if not key provided, calls create, otherwise calls save
     * @param		Custodian	custodian
     * @return		Custodian 
     */
	@PostMapping("/create")
    public Custodian create( @RequestBody(required=true) CreateCustodianCommand command ) {
    	Custodian entity = null;
		try {       
        	
			entity = CustodianBusinessDelegate.getCustodianInstance().createCustodian( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Custodian.  if no key provided, calls create, otherwise calls save
     * @param		Custodian custodian
     * @return		Custodian
     */
	@PutMapping("/update")
    public Custodian update( @RequestBody(required=true) UpdateCustodianCommand command ) {
		Custodian entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateCustodianCommand
			// -----------------------------------------------
			entity = CustodianBusinessDelegate.getCustodianInstance().updateCustodian(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "CustodianController:update() - successfully update Custodian - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Custodian entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteCustodianCommand command ) {                
    	try {
        	CustodianBusinessDelegate delegate = CustodianBusinessDelegate.getCustodianInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Custodian with key " + command.getCustodianId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Custodian using a UUID
     * @param		UUID uuid 
     * @return		Custodian
     */    
    @GetMapping("/load")
    public Custodian load( @RequestParam(required=true) UUID uuid ) {    	
    	Custodian entity = null;

    	try {  
    		entity = CustodianBusinessDelegate.getCustodianInstance().getCustodian( new CustodianFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Custodian using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Custodian business objects
     * @return		Set<Custodian>
     */
    @GetMapping("/")
    public List<Custodian> loadAll() {                
    	List<Custodian> custodianList = null;
        
    	try {
            // load the Custodian
            custodianList = CustodianBusinessDelegate.getCustodianInstance().getAllCustodian();
            
            if ( custodianList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Custodians" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Custodians ", exc );
        	return null;
        }

        return custodianList;
                            
    }


    /**
     * save Accounts on Custodian
     * @param		command AssignAccountsToCustodianCommand
     */     
	@PutMapping("/addToAccounts")
	public void addToAccounts( @RequestBody(required=true) AssignAccountsToCustodianCommand command ) {
		try {
			CustodianBusinessDelegate.getCustodianInstance().addToAccounts( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Accounts", exc );
		}
	}

    /**
     * remove Accounts on Custodian
     * @param		command RemoveAccountsFromCustodianCommand
     */     	
	@PutMapping("/removeFromAccounts")
	public void removeFromAccounts( 	@RequestBody(required=true) RemoveAccountsFromCustodianCommand command )
	{		
		try {
			CustodianBusinessDelegate.getCustodianInstance().removeFromAccounts( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Accounts", exc );
		}
	}

    /**
     * save Transfers on Custodian
     * @param		command AssignTransfersToCustodianCommand
     */     
	@PutMapping("/addToTransfers")
	public void addToTransfers( @RequestBody(required=true) AssignTransfersToCustodianCommand command ) {
		try {
			CustodianBusinessDelegate.getCustodianInstance().addToTransfers( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Transfers", exc );
		}
	}

    /**
     * remove Transfers on Custodian
     * @param		command RemoveTransfersFromCustodianCommand
     */     	
	@PutMapping("/removeFromTransfers")
	public void removeFromTransfers( 	@RequestBody(required=true) RemoveTransfersFromCustodianCommand command )
	{		
		try {
			CustodianBusinessDelegate.getCustodianInstance().removeFromTransfers( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Transfers", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Custodian custodian = null;
    private static final Logger LOGGER = Logger.getLogger(CustodianRestController.class.getName());
    
}
