/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * DocumentRestController as REST API
 *
 * <p>Exposes REST endpoints for the Document entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	DocumentService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateDocumentCommand</li>
 *      <li></li>UpdateDocumentCommand</li>
 *      <liDeleteDocumentCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Document")
public class DocumentRestController extends BaseSpringRestController {

	public DocumentRestController( DocumentService service ) {
		this.service = service;
	}
    /**
     * Handles create a Document.  if not key provided, calls create, otherwise calls save
     * @param		Document	document
     * @return		Document 
     */
	@PostMapping("/create")
    public Document create( @RequestBody(required=true) CreateDocumentCommand command ) {
    	Document entity = null;
		try {       
        	
			entity = service.createDocument( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Document.  if no key provided, calls create, otherwise calls save
     * @param		Document document
     * @return		Document
     */
	@PutMapping("/update")
    public Document update( @RequestBody(required=true) UpdateDocumentCommand command ) {
		Document entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateDocumentCommand
			// -----------------------------------------------
			entity = service.updateDocument(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "DocumentController:update() - successfully update Document - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Document entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteDocumentCommand command ) {                
    	try {
        	DocumentService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Document with key " + command.getDocumentId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Document using a UUID
     * @param		UUID uuid 
     * @return		Document
     */    
    @GetMapping("/load")
    public Document load( @RequestParam(required=true) UUID uuid ) {    	
    	Document entity = null;

    	try {  
    		entity = service.getDocument( new DocumentFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Document using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Document business objects
     * @return		Set<Document>
     */
    @GetMapping("/")
    public List<Document> loadAll() {                
    	List<Document> documentList = null;
        
    	try {
            // load the Document
            documentList = service.getAllDocument();
            
            if ( documentList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Documents" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Documents ", exc );
        	return null;
        }

        return documentList;
                            
    }

    /**
     * save Client on Document
     * @param		command AssignClientToDocumentCommand
     */     
	@PutMapping("/assignClient")
	public void assignClient( @RequestBody AssignClientToDocumentCommand command ) {
		try {
			service.assignClient( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Client", exc );
        }
	}

    /**
     * unassign Client on Document
     * @param		 command UnAssignClientFromDocumentCommand
     */     
	@PutMapping("/unAssignClient")
	public void unAssignClient( @RequestBody(required=true)  UnAssignClientFromDocumentCommand command ) {
		try {
			service.unAssignClient( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Client", exc );
		}
	}
	
    /**
     * save KycRecord on Document
     * @param		command AssignKycRecordToDocumentCommand
     */     
	@PutMapping("/assignKycRecord")
	public void assignKycRecord( @RequestBody AssignKycRecordToDocumentCommand command ) {
		try {
			service.assignKycRecord( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign KycRecord", exc );
        }
	}

    /**
     * unassign KycRecord on Document
     * @param		 command UnAssignKycRecordFromDocumentCommand
     */     
	@PutMapping("/unAssignKycRecord")
	public void unAssignKycRecord( @RequestBody(required=true)  UnAssignKycRecordFromDocumentCommand command ) {
		try {
			service.unAssignKycRecord( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign KycRecord", exc );
		}
	}
	
    /**
     * save Agreement on Document
     * @param		command AssignAgreementToDocumentCommand
     */     
	@PutMapping("/assignAgreement")
	public void assignAgreement( @RequestBody AssignAgreementToDocumentCommand command ) {
		try {
			service.assignAgreement( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Agreement", exc );
        }
	}

    /**
     * unassign Agreement on Document
     * @param		 command UnAssignAgreementFromDocumentCommand
     */     
	@PutMapping("/unAssignAgreement")
	public void unAssignAgreement( @RequestBody(required=true)  UnAssignAgreementFromDocumentCommand command ) {
		try {
			service.unAssignAgreement( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Agreement", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Document document = null;
	protected DocumentService service = null;
    private static final Logger LOGGER = Logger.getLogger(DocumentRestController.class.getName());
    
}
