/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * KycRecordRestController as REST API
 *
 * <p>Exposes REST endpoints for the KycRecord entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	KycRecordService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateKycRecordCommand</li>
 *      <li></li>UpdateKycRecordCommand</li>
 *      <liDeleteKycRecordCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/KycRecord")
public class KycRecordRestController extends BaseSpringRestController {

	public KycRecordRestController( KycRecordService service ) {
		this.service = service;
	}
    /**
     * Handles create a KycRecord.  if not key provided, calls create, otherwise calls save
     * @param		KycRecord	kycRecord
     * @return		KycRecord 
     */
	@PostMapping("/create")
    public KycRecord create( @RequestBody(required=true) CreateKycRecordCommand command ) {
    	KycRecord entity = null;
		try {       
        	
			entity = service.createKycRecord( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a KycRecord.  if no key provided, calls create, otherwise calls save
     * @param		KycRecord kycRecord
     * @return		KycRecord
     */
	@PutMapping("/update")
    public KycRecord update( @RequestBody(required=true) UpdateKycRecordCommand command ) {
		KycRecord entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateKycRecordCommand
			// -----------------------------------------------
			entity = service.updateKycRecord(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "KycRecordController:update() - successfully update KycRecord - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a KycRecord entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteKycRecordCommand command ) {                
    	try {
        	KycRecordService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted KycRecord with key " + command.getKycRecordId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a KycRecord using a UUID
     * @param		UUID uuid 
     * @return		KycRecord
     */    
    @GetMapping("/load")
    public KycRecord load( @RequestParam(required=true) UUID uuid ) {    	
    	KycRecord entity = null;

    	try {  
    		entity = service.getKycRecord( new KycRecordFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load KycRecord using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all KycRecord business objects
     * @return		Set<KycRecord>
     */
    @GetMapping("/")
    public List<KycRecord> loadAll() {                
    	List<KycRecord> kycRecordList = null;
        
    	try {
            // load the KycRecord
            kycRecordList = service.getAllKycRecord();
            
            if ( kycRecordList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all KycRecords" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all KycRecords ", exc );
        	return null;
        }

        return kycRecordList;
                            
    }

    /**
     * save Client on KycRecord
     * @param		command AssignClientToKycRecordCommand
     */     
	@PutMapping("/assignClient")
	public void assignClient( @RequestBody AssignClientToKycRecordCommand command ) {
		try {
			service.assignClient( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Client", exc );
        }
	}

    /**
     * unassign Client on KycRecord
     * @param		 command UnAssignClientFromKycRecordCommand
     */     
	@PutMapping("/unAssignClient")
	public void unAssignClient( @RequestBody(required=true)  UnAssignClientFromKycRecordCommand command ) {
		try {
			service.unAssignClient( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Client", exc );
		}
	}
	

    /**
     * save Documents on KycRecord
     * @param		command AssignDocumentsToKycRecordCommand
     */     
	@PutMapping("/addToDocuments")
	public void addToDocuments( @RequestBody(required=true) AssignDocumentsToKycRecordCommand command ) {
		try {
			service.addToDocuments( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Documents", exc );
		}
	}

    /**
     * remove Documents on KycRecord
     * @param		command RemoveDocumentsFromKycRecordCommand
     */     	
	@PutMapping("/removeFromDocuments")
	public void removeFromDocuments( 	@RequestBody(required=true) RemoveDocumentsFromKycRecordCommand command )
	{		
		try {
			service.removeFromDocuments( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Documents", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected KycRecord kycRecord = null;
	protected KycRecordService service = null;
    private static final Logger LOGGER = Logger.getLogger(KycRecordRestController.class.getName());
    
}
