/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * OfficeRestController as REST API
 *
 * <p>Exposes REST endpoints for the Office entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	OfficeService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateOfficeCommand</li>
 *      <li></li>UpdateOfficeCommand</li>
 *      <liDeleteOfficeCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Office")
public class OfficeRestController extends BaseSpringRestController {

	public OfficeRestController( OfficeService service ) {
		this.service = service;
	}
    /**
     * Handles create a Office.  if not key provided, calls create, otherwise calls save
     * @param		Office	office
     * @return		Office 
     */
	@PostMapping("/create")
    public Office create( @RequestBody(required=true) CreateOfficeCommand command ) {
    	Office entity = null;
		try {       
        	
			entity = service.createOffice( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Office.  if no key provided, calls create, otherwise calls save
     * @param		Office office
     * @return		Office
     */
	@PutMapping("/update")
    public Office update( @RequestBody(required=true) UpdateOfficeCommand command ) {
		Office entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateOfficeCommand
			// -----------------------------------------------
			entity = service.updateOffice(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "OfficeController:update() - successfully update Office - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Office entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteOfficeCommand command ) {                
    	try {
        	OfficeService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Office with key " + command.getOfficeId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Office using a UUID
     * @param		UUID uuid 
     * @return		Office
     */    
    @GetMapping("/load")
    public Office load( @RequestParam(required=true) UUID uuid ) {    	
    	Office entity = null;

    	try {  
    		entity = service.getOffice( new OfficeFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Office using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Office business objects
     * @return		Set<Office>
     */
    @GetMapping("/")
    public List<Office> loadAll() {                
    	List<Office> officeList = null;
        
    	try {
            // load the Office
            officeList = service.getAllOffice();
            
            if ( officeList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Offices" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Offices ", exc );
        	return null;
        }

        return officeList;
                            
    }

    /**
     * save Firm on Office
     * @param		command AssignFirmToOfficeCommand
     */     
	@PutMapping("/assignFirm")
	public void assignFirm( @RequestBody AssignFirmToOfficeCommand command ) {
		try {
			service.assignFirm( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Firm", exc );
        }
	}

    /**
     * unassign Firm on Office
     * @param		 command UnAssignFirmFromOfficeCommand
     */     
	@PutMapping("/unAssignFirm")
	public void unAssignFirm( @RequestBody(required=true)  UnAssignFirmFromOfficeCommand command ) {
		try {
			service.unAssignFirm( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Firm", exc );
		}
	}
	

    /**
     * save Advisors on Office
     * @param		command AssignAdvisorsToOfficeCommand
     */     
	@PutMapping("/addToAdvisors")
	public void addToAdvisors( @RequestBody(required=true) AssignAdvisorsToOfficeCommand command ) {
		try {
			service.addToAdvisors( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Advisors", exc );
		}
	}

    /**
     * remove Advisors on Office
     * @param		command RemoveAdvisorsFromOfficeCommand
     */     	
	@PutMapping("/removeFromAdvisors")
	public void removeFromAdvisors( 	@RequestBody(required=true) RemoveAdvisorsFromOfficeCommand command )
	{		
		try {
			service.removeFromAdvisors( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Advisors", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Office office = null;
	protected OfficeService service = null;
    private static final Logger LOGGER = Logger.getLogger(OfficeRestController.class.getName());
    
}
