/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * PositionRestController as REST API
 *
 * <p>Exposes REST endpoints for the Position entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	PositionBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreatePositionCommand</li>
 *      <li></li>UpdatePositionCommand</li>
 *      <liDeletePositionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Position")
public class PositionRestController extends BaseSpringRestController {

    /**
     * Handles create a Position.  if not key provided, calls create, otherwise calls save
     * @param		Position	position
     * @return		Position 
     */
	@PostMapping("/create")
    public Position create( @RequestBody(required=true) CreatePositionCommand command ) {
    	Position entity = null;
		try {       
        	
			entity = PositionBusinessDelegate.getPositionInstance().createPosition( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Position.  if no key provided, calls create, otherwise calls save
     * @param		Position position
     * @return		Position
     */
	@PutMapping("/update")
    public Position update( @RequestBody(required=true) UpdatePositionCommand command ) {
		Position entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdatePositionCommand
			// -----------------------------------------------
			entity = PositionBusinessDelegate.getPositionInstance().updatePosition(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "PositionController:update() - successfully update Position - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Position entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeletePositionCommand command ) {                
    	try {
        	PositionBusinessDelegate delegate = PositionBusinessDelegate.getPositionInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Position with key " + command.getPositionId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Position using a UUID
     * @param		UUID uuid 
     * @return		Position
     */    
    @GetMapping("/load")
    public Position load( @RequestParam(required=true) UUID uuid ) {    	
    	Position entity = null;

    	try {  
    		entity = PositionBusinessDelegate.getPositionInstance().getPosition( new PositionFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Position using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Position business objects
     * @return		Set<Position>
     */
    @GetMapping("/")
    public List<Position> loadAll() {                
    	List<Position> positionList = null;
        
    	try {
            // load the Position
            positionList = PositionBusinessDelegate.getPositionInstance().getAllPosition();
            
            if ( positionList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Positions" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Positions ", exc );
        	return null;
        }

        return positionList;
                            
    }

    /**
     * save Portfolio on Position
     * @param		command AssignPortfolioToPositionCommand
     */     
	@PutMapping("/assignPortfolio")
	public void assignPortfolio( @RequestBody AssignPortfolioToPositionCommand command ) {
		try {
			PositionBusinessDelegate.getPositionInstance().assignPortfolio( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Portfolio", exc );
        }
	}

    /**
     * unassign Portfolio on Position
     * @param		 command UnAssignPortfolioFromPositionCommand
     */     
	@PutMapping("/unAssignPortfolio")
	public void unAssignPortfolio( @RequestBody(required=true)  UnAssignPortfolioFromPositionCommand command ) {
		try {
			PositionBusinessDelegate.getPositionInstance().unAssignPortfolio( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Portfolio", exc );
		}
	}
	
    /**
     * save Security on Position
     * @param		command AssignSecurityToPositionCommand
     */     
	@PutMapping("/assignSecurity")
	public void assignSecurity( @RequestBody AssignSecurityToPositionCommand command ) {
		try {
			PositionBusinessDelegate.getPositionInstance().assignSecurity( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Security", exc );
        }
	}

    /**
     * unassign Security on Position
     * @param		 command UnAssignSecurityFromPositionCommand
     */     
	@PutMapping("/unAssignSecurity")
	public void unAssignSecurity( @RequestBody(required=true)  UnAssignSecurityFromPositionCommand command ) {
		try {
			PositionBusinessDelegate.getPositionInstance().unAssignSecurity( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Security", exc );
		}
	}
	

    /**
     * save TaxLots on Position
     * @param		command AssignTaxLotsToPositionCommand
     */     
	@PutMapping("/addToTaxLots")
	public void addToTaxLots( @RequestBody(required=true) AssignTaxLotsToPositionCommand command ) {
		try {
			PositionBusinessDelegate.getPositionInstance().addToTaxLots( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set TaxLots", exc );
		}
	}

    /**
     * remove TaxLots on Position
     * @param		command RemoveTaxLotsFromPositionCommand
     */     	
	@PutMapping("/removeFromTaxLots")
	public void removeFromTaxLots( 	@RequestBody(required=true) RemoveTaxLotsFromPositionCommand command )
	{		
		try {
			PositionBusinessDelegate.getPositionInstance().removeFromTaxLots( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set TaxLots", exc );
		}
	}

    /**
     * save Transactions on Position
     * @param		command AssignTransactionsToPositionCommand
     */     
	@PutMapping("/addToTransactions")
	public void addToTransactions( @RequestBody(required=true) AssignTransactionsToPositionCommand command ) {
		try {
			PositionBusinessDelegate.getPositionInstance().addToTransactions( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to add to Set Transactions", exc );
		}
	}

    /**
     * remove Transactions on Position
     * @param		command RemoveTransactionsFromPositionCommand
     */     	
	@PutMapping("/removeFromTransactions")
	public void removeFromTransactions( 	@RequestBody(required=true) RemoveTransactionsFromPositionCommand command )
	{		
		try {
			PositionBusinessDelegate.getPositionInstance().removeFromTransactions( command );
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to remove from Set Transactions", exc );
		}
	}




//************************************************************************    
// Attributes
//************************************************************************
    protected Position position = null;
    private static final Logger LOGGER = Logger.getLogger(PositionRestController.class.getName());
    
}
