/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * ProposalRestController as REST API
 *
 * <p>Exposes REST endpoints for the Proposal entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	ProposalBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateProposalCommand</li>
 *      <li></li>UpdateProposalCommand</li>
 *      <liDeleteProposalCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Proposal")
public class ProposalRestController extends BaseSpringRestController {

    /**
     * Handles create a Proposal.  if not key provided, calls create, otherwise calls save
     * @param		Proposal	proposal
     * @return		Proposal 
     */
	@PostMapping("/create")
    public Proposal create( @RequestBody(required=true) CreateProposalCommand command ) {
    	Proposal entity = null;
		try {       
        	
			entity = ProposalBusinessDelegate.getProposalInstance().createProposal( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Proposal.  if no key provided, calls create, otherwise calls save
     * @param		Proposal proposal
     * @return		Proposal
     */
	@PutMapping("/update")
    public Proposal update( @RequestBody(required=true) UpdateProposalCommand command ) {
		Proposal entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateProposalCommand
			// -----------------------------------------------
			entity = ProposalBusinessDelegate.getProposalInstance().updateProposal(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "ProposalController:update() - successfully update Proposal - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Proposal entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteProposalCommand command ) {                
    	try {
        	ProposalBusinessDelegate delegate = ProposalBusinessDelegate.getProposalInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Proposal with key " + command.getProposalId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Proposal using a UUID
     * @param		UUID uuid 
     * @return		Proposal
     */    
    @GetMapping("/load")
    public Proposal load( @RequestParam(required=true) UUID uuid ) {    	
    	Proposal entity = null;

    	try {  
    		entity = ProposalBusinessDelegate.getProposalInstance().getProposal( new ProposalFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Proposal using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Proposal business objects
     * @return		Set<Proposal>
     */
    @GetMapping("/")
    public List<Proposal> loadAll() {                
    	List<Proposal> proposalList = null;
        
    	try {
            // load the Proposal
            proposalList = ProposalBusinessDelegate.getProposalInstance().getAllProposal();
            
            if ( proposalList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Proposals" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Proposals ", exc );
        	return null;
        }

        return proposalList;
                            
    }

    /**
     * save Household on Proposal
     * @param		command AssignHouseholdToProposalCommand
     */     
	@PutMapping("/assignHousehold")
	public void assignHousehold( @RequestBody AssignHouseholdToProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().assignHousehold( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Household", exc );
        }
	}

    /**
     * unassign Household on Proposal
     * @param		 command UnAssignHouseholdFromProposalCommand
     */     
	@PutMapping("/unAssignHousehold")
	public void unAssignHousehold( @RequestBody(required=true)  UnAssignHouseholdFromProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().unAssignHousehold( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Household", exc );
		}
	}
	
    /**
     * save Advisor on Proposal
     * @param		command AssignAdvisorToProposalCommand
     */     
	@PutMapping("/assignAdvisor")
	public void assignAdvisor( @RequestBody AssignAdvisorToProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().assignAdvisor( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Advisor", exc );
        }
	}

    /**
     * unassign Advisor on Proposal
     * @param		 command UnAssignAdvisorFromProposalCommand
     */     
	@PutMapping("/unAssignAdvisor")
	public void unAssignAdvisor( @RequestBody(required=true)  UnAssignAdvisorFromProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().unAssignAdvisor( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Advisor", exc );
		}
	}
	
    /**
     * save ModelPortfolio on Proposal
     * @param		command AssignModelPortfolioToProposalCommand
     */     
	@PutMapping("/assignModelPortfolio")
	public void assignModelPortfolio( @RequestBody AssignModelPortfolioToProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().assignModelPortfolio( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign ModelPortfolio", exc );
        }
	}

    /**
     * unassign ModelPortfolio on Proposal
     * @param		 command UnAssignModelPortfolioFromProposalCommand
     */     
	@PutMapping("/unAssignModelPortfolio")
	public void unAssignModelPortfolio( @RequestBody(required=true)  UnAssignModelPortfolioFromProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().unAssignModelPortfolio( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign ModelPortfolio", exc );
		}
	}
	
    /**
     * save Account on Proposal
     * @param		command AssignAccountToProposalCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().assignAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Account", exc );
        }
	}

    /**
     * unassign Account on Proposal
     * @param		 command UnAssignAccountFromProposalCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromProposalCommand command ) {
		try {
			ProposalBusinessDelegate.getProposalInstance().unAssignAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Account", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Proposal proposal = null;
    private static final Logger LOGGER = Logger.getLogger(ProposalRestController.class.getName());
    
}
