/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * StandingInstructionRestController as REST API
 *
 * <p>Exposes REST endpoints for the StandingInstruction entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	StandingInstructionBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateStandingInstructionCommand</li>
 *      <li></li>UpdateStandingInstructionCommand</li>
 *      <liDeleteStandingInstructionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/StandingInstruction")
public class StandingInstructionRestController extends BaseSpringRestController {

    /**
     * Handles create a StandingInstruction.  if not key provided, calls create, otherwise calls save
     * @param		StandingInstruction	standingInstruction
     * @return		StandingInstruction 
     */
	@PostMapping("/create")
    public StandingInstruction create( @RequestBody(required=true) CreateStandingInstructionCommand command ) {
    	StandingInstruction entity = null;
		try {       
        	
			entity = StandingInstructionBusinessDelegate.getStandingInstructionInstance().createStandingInstruction( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a StandingInstruction.  if no key provided, calls create, otherwise calls save
     * @param		StandingInstruction standingInstruction
     * @return		StandingInstruction
     */
	@PutMapping("/update")
    public StandingInstruction update( @RequestBody(required=true) UpdateStandingInstructionCommand command ) {
		StandingInstruction entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateStandingInstructionCommand
			// -----------------------------------------------
			entity = StandingInstructionBusinessDelegate.getStandingInstructionInstance().updateStandingInstruction(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "StandingInstructionController:update() - successfully update StandingInstruction - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a StandingInstruction entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteStandingInstructionCommand command ) {                
    	try {
        	StandingInstructionBusinessDelegate delegate = StandingInstructionBusinessDelegate.getStandingInstructionInstance();

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted StandingInstruction with key " + command.getStandingInstructionId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a StandingInstruction using a UUID
     * @param		UUID uuid 
     * @return		StandingInstruction
     */    
    @GetMapping("/load")
    public StandingInstruction load( @RequestParam(required=true) UUID uuid ) {    	
    	StandingInstruction entity = null;

    	try {  
    		entity = StandingInstructionBusinessDelegate.getStandingInstructionInstance().getStandingInstruction( new StandingInstructionFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load StandingInstruction using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all StandingInstruction business objects
     * @return		Set<StandingInstruction>
     */
    @GetMapping("/")
    public List<StandingInstruction> loadAll() {                
    	List<StandingInstruction> standingInstructionList = null;
        
    	try {
            // load the StandingInstruction
            standingInstructionList = StandingInstructionBusinessDelegate.getStandingInstructionInstance().getAllStandingInstruction();
            
            if ( standingInstructionList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all StandingInstructions" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all StandingInstructions ", exc );
        	return null;
        }

        return standingInstructionList;
                            
    }

    /**
     * save Account on StandingInstruction
     * @param		command AssignAccountToStandingInstructionCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToStandingInstructionCommand command ) {
		try {
			StandingInstructionBusinessDelegate.getStandingInstructionInstance().assignAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Account", exc );
        }
	}

    /**
     * unassign Account on StandingInstruction
     * @param		 command UnAssignAccountFromStandingInstructionCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromStandingInstructionCommand command ) {
		try {
			StandingInstructionBusinessDelegate.getStandingInstructionInstance().unAssignAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Account", exc );
		}
	}
	
    /**
     * save DestinationAccount on StandingInstruction
     * @param		command AssignDestinationAccountToStandingInstructionCommand
     */     
	@PutMapping("/assignDestinationAccount")
	public void assignDestinationAccount( @RequestBody AssignDestinationAccountToStandingInstructionCommand command ) {
		try {
			StandingInstructionBusinessDelegate.getStandingInstructionInstance().assignDestinationAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign DestinationAccount", exc );
        }
	}

    /**
     * unassign DestinationAccount on StandingInstruction
     * @param		 command UnAssignDestinationAccountFromStandingInstructionCommand
     */     
	@PutMapping("/unAssignDestinationAccount")
	public void unAssignDestinationAccount( @RequestBody(required=true)  UnAssignDestinationAccountFromStandingInstructionCommand command ) {
		try {
			StandingInstructionBusinessDelegate.getStandingInstructionInstance().unAssignDestinationAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign DestinationAccount", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected StandingInstruction standingInstruction = null;
    private static final Logger LOGGER = Logger.getLogger(StandingInstructionRestController.class.getName());
    
}
