/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TradeRestController as REST API
 *
 * <p>Exposes REST endpoints for the Trade entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TradeService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTradeCommand</li>
 *      <li></li>UpdateTradeCommand</li>
 *      <liDeleteTradeCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Trade")
public class TradeRestController extends BaseSpringRestController {

	public TradeRestController( TradeService service ) {
		this.service = service;
	}
    /**
     * Handles create a Trade.  if not key provided, calls create, otherwise calls save
     * @param		Trade	trade
     * @return		Trade 
     */
	@PostMapping("/create")
    public Trade create( @RequestBody(required=true) CreateTradeCommand command ) {
    	Trade entity = null;
		try {       
        	
			entity = service.createTrade( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Trade.  if no key provided, calls create, otherwise calls save
     * @param		Trade trade
     * @return		Trade
     */
	@PutMapping("/update")
    public Trade update( @RequestBody(required=true) UpdateTradeCommand command ) {
		Trade entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateTradeCommand
			// -----------------------------------------------
			entity = service.updateTrade(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "TradeController:update() - successfully update Trade - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Trade entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTradeCommand command ) {                
    	try {
        	TradeService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Trade with key " + command.getTradeId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Trade using a UUID
     * @param		UUID uuid 
     * @return		Trade
     */    
    @GetMapping("/load")
    public Trade load( @RequestParam(required=true) UUID uuid ) {    	
    	Trade entity = null;

    	try {  
    		entity = service.getTrade( new TradeFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Trade using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Trade business objects
     * @return		Set<Trade>
     */
    @GetMapping("/")
    public List<Trade> loadAll() {                
    	List<Trade> tradeList = null;
        
    	try {
            // load the Trade
            tradeList = service.getAllTrade();
            
            if ( tradeList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Trades" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Trades ", exc );
        	return null;
        }

        return tradeList;
                            
    }

    /**
     * save Order on Trade
     * @param		command AssignOrderToTradeCommand
     */     
	@PutMapping("/assignOrder")
	public void assignOrder( @RequestBody AssignOrderToTradeCommand command ) {
		try {
			service.assignOrder( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Order", exc );
        }
	}

    /**
     * unassign Order on Trade
     * @param		 command UnAssignOrderFromTradeCommand
     */     
	@PutMapping("/unAssignOrder")
	public void unAssignOrder( @RequestBody(required=true)  UnAssignOrderFromTradeCommand command ) {
		try {
			service.unAssignOrder( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Order", exc );
		}
	}
	
    /**
     * save Account on Trade
     * @param		command AssignAccountToTradeCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToTradeCommand command ) {
		try {
			service.assignAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Account", exc );
        }
	}

    /**
     * unassign Account on Trade
     * @param		 command UnAssignAccountFromTradeCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromTradeCommand command ) {
		try {
			service.unAssignAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Account", exc );
		}
	}
	
    /**
     * save Security on Trade
     * @param		command AssignSecurityToTradeCommand
     */     
	@PutMapping("/assignSecurity")
	public void assignSecurity( @RequestBody AssignSecurityToTradeCommand command ) {
		try {
			service.assignSecurity( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Security", exc );
        }
	}

    /**
     * unassign Security on Trade
     * @param		 command UnAssignSecurityFromTradeCommand
     */     
	@PutMapping("/unAssignSecurity")
	public void unAssignSecurity( @RequestBody(required=true)  UnAssignSecurityFromTradeCommand command ) {
		try {
			service.unAssignSecurity( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Security", exc );
		}
	}
	
    /**
     * save Transaction on Trade
     * @param		command AssignTransactionToTradeCommand
     */     
	@PutMapping("/assignTransaction")
	public void assignTransaction( @RequestBody AssignTransactionToTradeCommand command ) {
		try {
			service.assignTransaction( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Transaction", exc );
        }
	}

    /**
     * unassign Transaction on Trade
     * @param		 command UnAssignTransactionFromTradeCommand
     */     
	@PutMapping("/unAssignTransaction")
	public void unAssignTransaction( @RequestBody(required=true)  UnAssignTransactionFromTradeCommand command ) {
		try {
			service.unAssignTransaction( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Transaction", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Trade trade = null;
	protected TradeService service = null;
    private static final Logger LOGGER = Logger.getLogger(TradeRestController.class.getName());
    
}
