/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * TransactionRestController as REST API
 *
 * <p>Exposes REST endpoints for the Transaction entity.</p>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	TransactionService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateTransactionCommand</li>
 *      <li></li>UpdateTransactionCommand</li>
 *      <liDeleteTransactionCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/Transaction")
public class TransactionRestController extends BaseSpringRestController {

	public TransactionRestController( TransactionService service ) {
		this.service = service;
	}
    /**
     * Handles create a Transaction.  if not key provided, calls create, otherwise calls save
     * @param		Transaction	transaction
     * @return		Transaction 
     */
	@PostMapping("/create")
    public Transaction create( @RequestBody(required=true) CreateTransactionCommand command ) {
    	Transaction entity = null;
		try {       
        	
			entity = service.createTransaction( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return entity;
    }

    /**
     * Handles updating a Transaction.  if no key provided, calls create, otherwise calls save
     * @param		Transaction transaction
     * @return		Transaction
     */
	@PutMapping("/update")
    public Transaction update( @RequestBody(required=true) UpdateTransactionCommand command ) {
		Transaction entity = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateTransactionCommand
			// -----------------------------------------------
			entity = service.updateTransaction(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "TransactionController:update() - successfully update Transaction - " + exc.getMessage());        	
	    }		
		
		return entity;
	}
 
    /**
     * Handles deleting a Transaction entity
     * @param		command ${class.getDeleteCommandAlias()}
     */
    @DeleteMapping("/delete")    
    public void delete( @RequestBody(required=true) DeleteTransactionCommand command ) {                
    	try {
        	TransactionService delegate = service;

        	delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted Transaction with key " + command.getTransactionId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }

	}        
	
    /**
     * Handles loading a Transaction using a UUID
     * @param		UUID uuid 
     * @return		Transaction
     */    
    @GetMapping("/load")
    public Transaction load( @RequestParam(required=true) UUID uuid ) {    	
    	Transaction entity = null;

    	try {  
    		entity = service.getTransaction( new TransactionFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load Transaction using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all Transaction business objects
     * @return		Set<Transaction>
     */
    @GetMapping("/")
    public List<Transaction> loadAll() {                
    	List<Transaction> transactionList = null;
        
    	try {
            // load the Transaction
            transactionList = service.getAllTransaction();
            
            if ( transactionList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all Transactions" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all Transactions ", exc );
        	return null;
        }

        return transactionList;
                            
    }

    /**
     * save Account on Transaction
     * @param		command AssignAccountToTransactionCommand
     */     
	@PutMapping("/assignAccount")
	public void assignAccount( @RequestBody AssignAccountToTransactionCommand command ) {
		try {
			service.assignAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Account", exc );
        }
	}

    /**
     * unassign Account on Transaction
     * @param		 command UnAssignAccountFromTransactionCommand
     */     
	@PutMapping("/unAssignAccount")
	public void unAssignAccount( @RequestBody(required=true)  UnAssignAccountFromTransactionCommand command ) {
		try {
			service.unAssignAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Account", exc );
		}
	}
	
    /**
     * save Security on Transaction
     * @param		command AssignSecurityToTransactionCommand
     */     
	@PutMapping("/assignSecurity")
	public void assignSecurity( @RequestBody AssignSecurityToTransactionCommand command ) {
		try {
			service.assignSecurity( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Security", exc );
        }
	}

    /**
     * unassign Security on Transaction
     * @param		 command UnAssignSecurityFromTransactionCommand
     */     
	@PutMapping("/unAssignSecurity")
	public void unAssignSecurity( @RequestBody(required=true)  UnAssignSecurityFromTransactionCommand command ) {
		try {
			service.unAssignSecurity( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Security", exc );
		}
	}
	
    /**
     * save Order on Transaction
     * @param		command AssignOrderToTransactionCommand
     */     
	@PutMapping("/assignOrder")
	public void assignOrder( @RequestBody AssignOrderToTransactionCommand command ) {
		try {
			service.assignOrder( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Order", exc );
        }
	}

    /**
     * unassign Order on Transaction
     * @param		 command UnAssignOrderFromTransactionCommand
     */     
	@PutMapping("/unAssignOrder")
	public void unAssignOrder( @RequestBody(required=true)  UnAssignOrderFromTransactionCommand command ) {
		try {
			service.unAssignOrder( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Order", exc );
		}
	}
	
    /**
     * save Position on Transaction
     * @param		command AssignPositionToTransactionCommand
     */     
	@PutMapping("/assignPosition")
	public void assignPosition( @RequestBody AssignPositionToTransactionCommand command ) {
		try {
			service.assignPosition( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Position", exc );
        }
	}

    /**
     * unassign Position on Transaction
     * @param		 command UnAssignPositionFromTransactionCommand
     */     
	@PutMapping("/unAssignPosition")
	public void unAssignPosition( @RequestBody(required=true)  UnAssignPositionFromTransactionCommand command ) {
		try {
			service.unAssignPosition( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Position", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected Transaction transaction = null;
	protected TransactionService service = null;
    private static final Logger LOGGER = Logger.getLogger(TransactionRestController.class.getName());
    
}
