name: #appName GitHub Actions CI

on:
  workflow_dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
#GitHubActions_Steps_Uses()


      run: cd terraform && chmod 777 terraform.sh && ./terraform.sh install
