/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>AccountTransfer business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of AccountTransfer related services in the case of a AccountTransfer business related service failing.</li>
 * <li>Exposes a simpler, uniform AccountTransfer interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill AccountTransfer business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class AccountTransferService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public AccountTransferService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new AccountTransferEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(AccountTransferRepository.class) );
	}

	
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		AccountTransfer
    */
	public AccountTransfer createAccountTransfer( CreateAccountTransferCommand command )
    throws ProcessingException, IllegalArgumentException {

		AccountTransfer entity = new AccountTransfer();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	AccountTransferValidator.getInstance().validate( command );    

            entity.setAccountTransferId( command.getAccountTransferId() );
            entity.setRequestDate( command.getRequestDate() );
            entity.setCompletionDate( command.getCompletionDate() );
            entity.setTransferType( command.getTransferType() );
            entity.setStatus( command.getStatus() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of AccountTransfer {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create AccountTransfer - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateAccountTransferCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		AccountTransfer
    */
    public AccountTransfer updateAccountTransfer( UpdateAccountTransferCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    AccountTransfer entity = new AccountTransfer();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	AccountTransferValidator.getInstance().validate( command );    

            entity.setAccountTransferId( command.getAccountTransferId() );
            entity.setRequestDate( command.getRequestDate() );
            entity.setCompletionDate( command.getCompletionDate() );
            entity.setFromCustodian( command.getFromCustodian() );
            entity.setToCustodian( command.getToCustodian() );
            entity.setAccount( command.getAccount() );
            entity.setTransferType( command.getTransferType() );
            entity.setStatus( command.getStatus() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of AccountTransfer {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save AccountTransfer - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteAccountTransferCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteAccountTransferCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	AccountTransferValidator.getInstance().validate( command );    
        
        	id = command.getAccountTransferId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of AccountTransfer {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete AccountTransfer using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the AccountTransfer via AccountTransferFetchOneSummary
     * @param 	summary AccountTransferFetchOneSummary 
     * @return 	AccountTransferFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public AccountTransfer getAccountTransfer( AccountTransferFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "AccountTransferFetchOneSummary arg cannot be null" );
    	
    	AccountTransfer entity = null;
    	UUID id = summary.getAccountTransferId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	AccountTransferValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a AccountTransfer using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate AccountTransfer with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all AccountTransfers
     *
     * @return 	List<AccountTransfer> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<AccountTransfer> getAllAccountTransfer() 
    throws ProcessingException {
        List<AccountTransfer> list = null;

        try {        	
        	list = projector.findAll( new FindAllAccountTransferQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all AccountTransfer";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign FromCustodian on AccountTransfer
     * @param		command AssignFromCustodianToAccountTransferCommand	
     * @exception	ProcessingException
     */     
	public void assignFromCustodian( AssignFromCustodianToAccountTransferCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	AccountTransferValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignFromCustodian(command.getAccountTransferId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Custodian using id " + command.getAccountTransferId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign FromCustodian on AccountTransfer
     * @param		command UnAssignFromCustodianFromAccountTransferCommand
     * @exception	ProcessingException
     */     
	public void unAssignFromCustodian( UnAssignFromCustodianFromAccountTransferCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccountTransferValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignFromCustodian(command.getAccountTransferId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign FromCustodian on AccountTransfer";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign ToCustodian on AccountTransfer
     * @param		command AssignToCustodianToAccountTransferCommand	
     * @exception	ProcessingException
     */     
	public void assignToCustodian( AssignToCustodianToAccountTransferCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	AccountTransferValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignToCustodian(command.getAccountTransferId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Custodian using id " + command.getAccountTransferId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign ToCustodian on AccountTransfer
     * @param		command UnAssignToCustodianFromAccountTransferCommand
     * @exception	ProcessingException
     */     
	public void unAssignToCustodian( UnAssignToCustodianFromAccountTransferCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccountTransferValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignToCustodian(command.getAccountTransferId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign ToCustodian on AccountTransfer";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Account on AccountTransfer
     * @param		command AssignAccountToAccountTransferCommand	
     * @exception	ProcessingException
     */     
	public void assignAccount( AssignAccountToAccountTransferCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	AccountTransferValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignAccount(command.getAccountTransferId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Account using id " + command.getAccountTransferId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Account on AccountTransfer
     * @param		command UnAssignAccountFromAccountTransferCommand
     * @exception	ProcessingException
     */     
	public void unAssignAccount( UnAssignAccountFromAccountTransferCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	AccountTransferValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignAccount(command.getAccountTransferId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Account on AccountTransfer";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final AccountTransferEntityProjector projector;
	private AccountTransfer accountTransfer 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(AccountTransferService.class);
}
