/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Advisor business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Advisor related services in the case of a Advisor business related service failing.</li>
 * <li>Exposes a simpler, uniform Advisor interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Advisor business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class AdvisorService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
		/**
		 * Default Constructor
		 */
    public AdvisorService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

			this.identity		= identity;
			this.projector 		= new AdvisorEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
											applicationContext.getBean(AdvisorRepository.class) );
			this.validator		= applicationContext.getBean(AdvisorValidator.class) ;
		}


		/**
		 * Creates the provided command.
		 *
		 * @param		command ${class.getCreateCommandAlias()}
		 * @exception    BusinessException
		 * @exception	IllegalArgumentException
		 * @return		Advisor
		 */
			public Advisor createAdvisor( CreateAdvisorCommand command )
    		throws BusinessException, IllegalArgumentException {

			Advisor entity = new Advisor();

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

            entity.setAdvisorId( command.getAdvisorId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setLicenseNumber( command.getLicenseNumber() );
            entity.setRole( command.getRole() );

				// ------------------------------------------
				// persist a new one
				// ------------------------------------------
				entity = projector.create(entity);

				LOGGER.info( "done creating of Advisor {0} ", entity.toString() );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to create Advisor - " + exc;
				LOGGER.warn(  errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}

		/**
		 * Update the provided command.
		 * @param		command UpdateAdvisorCommand
		 * @exception    BusinessException
		 * @return		Advisor
		 */
		public Advisor updateAdvisor( UpdateAdvisorCommand command )
  	  	throws BusinessException {

			Advisor entity = new Advisor();

			try {

				// --------------------------------------
				// validate
				// --------------------------------------
				validator.validate( command );

            entity.setAdvisorId( command.getAdvisorId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setLicenseNumber( command.getLicenseNumber() );
            entity.setFirm( command.getFirm() );
            entity.setOffice( command.getOffice() );
            entity.setClients( command.getClients() );
            entity.setAdvisoryTeam( command.getAdvisoryTeam() );
            entity.setRole( command.getRole() );

				// ------------------------------------------
				// persist an existing one
				// ------------------------------------------
				entity = projector.update(entity);

				LOGGER.info( "done saving of Advisor {0} ", entity.toString() );
			}
			catch (Exception exc) {
				final String errMsg = "Unable to save Advisor - " + exc;
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}

			return entity;
		}

		/**
		 * Deletes the associatied value object
		 * @param		command DeleteAdvisorCommand
		 * @exception 	BusinessException
		 */
		public void delete( DeleteAdvisorCommand command )
    	throws BusinessException {
			UUID id = null;

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				id = command.getAdvisorId();

				// ------------------------------------------
				// delete the entity
				// ------------------------------------------
				projector.delete(id);

				LOGGER.info( "done deleting of Advisor {0} ", id );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to delete Advisor using Id = "  + id;
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}
		}

		/**
		 * Method to retrieve the Advisor via AdvisorFetchOneSummary
		 * @param 	summary AdvisorFetchOneSummary
		 * @return 	AdvisorFetchOneResponse
		 * @exception BusinessException - Thrown if processing any related problems
		 */
    public Advisor getAdvisor( AdvisorFetchOneSummary summary ) 
    throws BusinessException {

			if( summary == null )
				throw new IllegalArgumentException( "AdvisorFetchOneSummary arg cannot be null" );

			Advisor entity = null;
			UUID id = summary.getAdvisorId();

			try {
				// --------------------------------------
				// validate the fetch one summary
				// --------------------------------------
				validator.validate( summary );

				// --------------------------------------
				// find a Advisor using the provided id
				// --------------------------------------
				entity = projector.find( id );
			}
			catch( Exception exc ) {
				final String errMsg = "Unable to locate Advisor with id " + id;
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}


		/**
		 * Method to retrieve a collection of all Advisors
		 *
		 * @return 	List<Advisor>
		 * @exception BusinessException Thrown if any problems
		 */
    public List<Advisor> getAllAdvisor() 
    throws BusinessException {
			List<Advisor> list = null;

			try {
				list = projector.findAll( new FindAllAdvisorQuery() );
			}
			catch( Exception exc ) {
				String errMsg = "Failed to get all Advisor";
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}

			return list;
		}

		/**
		 * assign Firm on Advisor
		 * @param		command AssignFirmToAdvisorCommand
		 * @exception	BusinessException
		 */
		public void assignFirm( AssignFirmToAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignFirm(command.getAdvisorId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get WealthFirm using id " + command.getAdvisorId();
				LOGGER.warn( msg );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * unAssign Firm on Advisor
		 * @param		command UnAssignFirmFromAdvisorCommand
		 * @exception	BusinessException
		 */
		public void unAssignFirm( UnAssignFirmFromAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignFirm(command.getAdvisorId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Firm on Advisor";
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}
		}
	
		/**
		 * assign Office on Advisor
		 * @param		command AssignOfficeToAdvisorCommand
		 * @exception	BusinessException
		 */
		public void assignOffice( AssignOfficeToAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignOffice(command.getAdvisorId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Office using id " + command.getAdvisorId();
				LOGGER.warn( msg );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * unAssign Office on Advisor
		 * @param		command UnAssignOfficeFromAdvisorCommand
		 * @exception	BusinessException
		 */
		public void unAssignOffice( UnAssignOfficeFromAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignOffice(command.getAdvisorId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Office on Advisor";
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}
		}
	
		/**
		 * assign AdvisoryTeam on Advisor
		 * @param		command AssignAdvisoryTeamToAdvisorCommand
		 * @exception	BusinessException
		 */
		public void assignAdvisoryTeam( AssignAdvisoryTeamToAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignAdvisoryTeam(command.getAdvisorId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get AdvisoryTeam using id " + command.getAdvisorId();
				LOGGER.warn( msg );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * unAssign AdvisoryTeam on Advisor
		 * @param		command UnAssignAdvisoryTeamFromAdvisorCommand
		 * @exception	BusinessException
		 */
		public void unAssignAdvisoryTeam( UnAssignAdvisoryTeamFromAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignAdvisoryTeam(command.getAdvisorId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign AdvisoryTeam on Advisor";
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}
		}
	

		/**
		 * add Client to Clients
		 * @param		command AssignClientsToAdvisorCommand
		 * @exception	BusinessException
		 */
		public void addToClients( AssignClientsToAdvisorCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.addToClients(command.getAdvisorId(), command.getAddTo());		}
			catch( Exception exc ) {
				final String msg = "Failed to add a Client as Clients to Advisor" ;
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}

		}

		/**
		 * remove Client from Clients
		 * @param		command RemoveClientsFromAdvisorCommand
		 * @exception	BusinessException
		 */
		public void removeFromClients( RemoveClientsFromAdvisorCommand command ) throws BusinessException {

			try {

				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.removeFromClients(command.getAdvisorId(), command.getRemoveFrom());

			}
			catch( Exception exc ) {
				final String msg = "Failed to remove child using Id " + command.getAdvisorId();
				LOGGER.warn(  msg, exc );
				throw new BusinessException( msg, exc );
			}
		}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final AdvisorEntityProjector projector;
	private final AdvisorValidator validator;
	private Advisor advisor 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(AdvisorService.class);
}
