/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
		package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>CashMovement business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of CashMovement related services in the case of a CashMovement business related service failing.</li>
 * <li>Exposes a simpler, uniform CashMovement interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill CashMovement business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class CashMovementService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
		/**
		 * Default Constructor
		 */
    public CashMovementService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

			this.identity		= identity;
			this.projector 		= new CashMovementEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
											applicationContext.getBean(CashMovementRepository.class) );
			this.validator		= applicationContext.getBean(CashMovementValidator.class) ;
		}


		/**
		 * Creates the provided command.
		 *
		 * @param		command ${class.getCreateCommandAlias()}
		 * @exception    ProcessingException
		 * @exception	IllegalArgumentException
		 * @return		CashMovement
		 */
			public CashMovement createCashMovement( CreateCashMovementCommand command )
    		throws ProcessingException, IllegalArgumentException {

			CashMovement entity = new CashMovement();

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

            entity.setCashMovementId( command.getCashMovementId() );
            entity.setAmount( command.getAmount() );
            entity.setValueDate( command.getValueDate() );
            entity.setDescription( command.getDescription() );
            entity.setMovementType( command.getMovementType() );

				// ------------------------------------------
				// persist a new one
				// ------------------------------------------
				entity = projector.create(entity);

				LOGGER.info( "done creating of CashMovement {0} ", entity.toString() );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to create CashMovement - " + exc;
				LOGGER.warn(  errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}

		/**
		 * Update the provided command.
		 * @param		command UpdateCashMovementCommand
		 * @exception    ProcessingException
		 * @exception  	IllegalArgumentException
		 * @return		CashMovement
		 */
		public CashMovement updateCashMovement( UpdateCashMovementCommand command )
    throws ProcessingException, IllegalArgumentException {

			CashMovement entity = new CashMovement();

			try {

				// --------------------------------------
				// validate
				// --------------------------------------
				validator.validate( command );

            entity.setCashMovementId( command.getCashMovementId() );
            entity.setAmount( command.getAmount() );
            entity.setValueDate( command.getValueDate() );
            entity.setDescription( command.getDescription() );
            entity.setAccount( command.getAccount() );
            entity.setRelatedInstruction( command.getRelatedInstruction() );
            entity.setRelatedTransaction( command.getRelatedTransaction() );
            entity.setMovementType( command.getMovementType() );

				// ------------------------------------------
				// persist an existing one
				// ------------------------------------------
				entity = projector.update(entity);

				LOGGER.info( "done saving of CashMovement {0} ", entity.toString() );
			}
			catch (Exception exc) {
				final String errMsg = "Unable to save CashMovement - " + exc;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}

			return entity;
		}

		/**
		 * Deletes the associatied value object
		 * @param		command DeleteCashMovementCommand
		 * @exception 	ProcessingException
		 */
		public void delete( DeleteCashMovementCommand command )
    throws ProcessingException, IllegalArgumentException {
			UUID id = null;

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				id = command.getCashMovementId();

				// ------------------------------------------
				// delete the entity
				// ------------------------------------------
				projector.delete(id);

				LOGGER.info( "done deleting of CashMovement {0} ", id );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to delete CashMovement using Id = "  + id;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}
		}

		/**
		 * Method to retrieve the CashMovement via CashMovementFetchOneSummary
		 * @param 	summary CashMovementFetchOneSummary
		 * @return 	CashMovementFetchOneResponse
		 * @exception ProcessingException - Thrown if processing any related problems
		 * @exception IllegalArgumentException
		 */
    public CashMovement getCashMovement( CashMovementFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {

			if( summary == null )
				throw new IllegalArgumentException( "CashMovementFetchOneSummary arg cannot be null" );

			CashMovement entity = null;
			UUID id = summary.getCashMovementId();

			try {
				// --------------------------------------
				// validate the fetch one summary
				// --------------------------------------
				validator.validate( summary );

				// --------------------------------------
				// find a CashMovement using the provided id
				// --------------------------------------
				entity = projector.find( id );
			}
			catch( Exception exc ) {
				final String errMsg = "Unable to locate CashMovement with id " + id;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}


		/**
		 * Method to retrieve a collection of all CashMovements
		 *
		 * @return 	List<CashMovement>
		 * @exception ProcessingException Thrown if any problems
		 */
    public List<CashMovement> getAllCashMovement() 
    throws ProcessingException {
			List<CashMovement> list = null;

			try {
				list = projector.findAll( new FindAllCashMovementQuery() );
			}
			catch( Exception exc ) {
				String errMsg = "Failed to get all CashMovement";
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return list;
		}

		/**
		 * assign Account on CashMovement
		 * @param		command AssignAccountToCashMovementCommand
		 * @exception	ProcessingException
		 */
		public void assignAccount( AssignAccountToCashMovementCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignAccount(command.getCashMovementId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Account using id " + command.getCashMovementId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign Account on CashMovement
		 * @param		command UnAssignAccountFromCashMovementCommand
		 * @exception	ProcessingException
		 */
		public void unAssignAccount( UnAssignAccountFromCashMovementCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignAccount(command.getCashMovementId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Account on CashMovement";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	
		/**
		 * assign RelatedInstruction on CashMovement
		 * @param		command AssignRelatedInstructionToCashMovementCommand
		 * @exception	ProcessingException
		 */
		public void assignRelatedInstruction( AssignRelatedInstructionToCashMovementCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignRelatedInstruction(command.getCashMovementId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get StandingInstruction using id " + command.getCashMovementId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign RelatedInstruction on CashMovement
		 * @param		command UnAssignRelatedInstructionFromCashMovementCommand
		 * @exception	ProcessingException
		 */
		public void unAssignRelatedInstruction( UnAssignRelatedInstructionFromCashMovementCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignRelatedInstruction(command.getCashMovementId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign RelatedInstruction on CashMovement";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	
		/**
		 * assign RelatedTransaction on CashMovement
		 * @param		command AssignRelatedTransactionToCashMovementCommand
		 * @exception	ProcessingException
		 */
		public void assignRelatedTransaction( AssignRelatedTransactionToCashMovementCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignRelatedTransaction(command.getCashMovementId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Transaction using id " + command.getCashMovementId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign RelatedTransaction on CashMovement
		 * @param		command UnAssignRelatedTransactionFromCashMovementCommand
		 * @exception	ProcessingException
		 */
		public void unAssignRelatedTransaction( UnAssignRelatedTransactionFromCashMovementCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignRelatedTransaction(command.getCashMovementId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign RelatedTransaction on CashMovement";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final CashMovementEntityProjector projector;
	private final {className}Validator validator;
	private CashMovement cashMovement 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(CashMovementService.class);
}

private <__TMP__> __TMP__ validator() {
}