/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Client business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Client related services in the case of a Client business related service failing.</li>
 * <li>Exposes a simpler, uniform Client interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Client business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class ClientService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
		/**
		 * Default Constructor
		 */
    public ClientService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

			this.identity		= identity;
			this.projector 		= new ClientEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
											applicationContext.getBean(ClientRepository.class) );
			this.validator		= applicationContext.getBean(ClientValidator.class) ;
		}


		/**
		 * Creates the provided command.
		 *
		 * @param		command ${class.getCreateCommandAlias()}
		 * @exception    BusinessException
		 * @exception	IllegalArgumentException
		 * @return		Client
		 */
			public Client createClient( CreateClientCommand command )
    		throws BusinessException, IllegalArgumentException {

			Client entity = new Client();

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

            entity.setClientId( command.getClientId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setTaxResidency( command.getTaxResidency() );
            entity.setDateOfBirth( command.getDateOfBirth() );
            entity.setEmail( command.getEmail() );

				// ------------------------------------------
				// persist a new one
				// ------------------------------------------
				entity = projector.create(entity);

				LOGGER.info( "done creating of Client {0} ", entity.toString() );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to create Client - " + exc;
				LOGGER.warn(  errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}

		/**
		 * Update the provided command.
		 * @param		command UpdateClientCommand
		 * @exception    BusinessException
		 * @return		Client
		 */
		public Client updateClient( UpdateClientCommand command )
  	  	throws BusinessException {

			Client entity = new Client();

			try {

				// --------------------------------------
				// validate
				// --------------------------------------
				validator.validate( command );

            entity.setClientId( command.getClientId() );
            entity.setFirstName( command.getFirstName() );
            entity.setLastName( command.getLastName() );
            entity.setTaxResidency( command.getTaxResidency() );
            entity.setDateOfBirth( command.getDateOfBirth() );
            entity.setEmail( command.getEmail() );
            entity.setHousehold( command.getHousehold() );
            entity.setAccounts( command.getAccounts() );
            entity.setDocuments( command.getDocuments() );
            entity.setBeneficiaries( command.getBeneficiaries() );
            entity.setKycRecord( command.getKycRecord() );
            entity.setAgreements( command.getAgreements() );

				// ------------------------------------------
				// persist an existing one
				// ------------------------------------------
				entity = projector.update(entity);

				LOGGER.info( "done saving of Client {0} ", entity.toString() );
			}
			catch (Exception exc) {
				final String errMsg = "Unable to save Client - " + exc;
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}

			return entity;
		}

		/**
		 * Deletes the associatied value object
		 * @param		command DeleteClientCommand
		 * @exception 	BusinessException
		 */
		public void delete( DeleteClientCommand command )
    	throws BusinessException {
			UUID id = null;

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				id = command.getClientId();

				// ------------------------------------------
				// delete the entity
				// ------------------------------------------
				projector.delete(id);

				LOGGER.info( "done deleting of Client {0} ", id );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to delete Client using Id = "  + id;
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}
		}

		/**
		 * Method to retrieve the Client via ClientFetchOneSummary
		 * @param 	summary ClientFetchOneSummary
		 * @return 	ClientFetchOneResponse
		 * @exception BusinessException - Thrown if processing any related problems
		 */
    public Client getClient( ClientFetchOneSummary summary ) 
    throws BusinessException {

			if( summary == null )
				throw new IllegalArgumentException( "ClientFetchOneSummary arg cannot be null" );

			Client entity = null;
			UUID id = summary.getClientId();

			try {
				// --------------------------------------
				// validate the fetch one summary
				// --------------------------------------
				validator.validate( summary );

				// --------------------------------------
				// find a Client using the provided id
				// --------------------------------------
				entity = projector.find( id );
			}
			catch( Exception exc ) {
				final String errMsg = "Unable to locate Client with id " + id;
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}


		/**
		 * Method to retrieve a collection of all Clients
		 *
		 * @return 	List<Client>
		 * @exception BusinessException Thrown if any problems
		 */
    public List<Client> getAllClient() 
    throws BusinessException {
			List<Client> list = null;

			try {
				list = projector.findAll( new FindAllClientQuery() );
			}
			catch( Exception exc ) {
				String errMsg = "Failed to get all Client";
				LOGGER.warn( errMsg, exc );
				throw new BusinessException( errMsg, exc );
			}
			finally {
			}

			return list;
		}

		/**
		 * assign Household on Client
		 * @param		command AssignHouseholdToClientCommand
		 * @exception	BusinessException
		 */
		public void assignHousehold( AssignHouseholdToClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignHousehold(command.getClientId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Household using id " + command.getClientId();
				LOGGER.warn( msg );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * unAssign Household on Client
		 * @param		command UnAssignHouseholdFromClientCommand
		 * @exception	BusinessException
		 */
		public void unAssignHousehold( UnAssignHouseholdFromClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignHousehold(command.getClientId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Household on Client";
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}
		}
	
		/**
		 * assign KycRecord on Client
		 * @param		command AssignKycRecordToClientCommand
		 * @exception	BusinessException
		 */
		public void assignKycRecord( AssignKycRecordToClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignKycRecord(command.getClientId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get KycRecord using id " + command.getClientId();
				LOGGER.warn( msg );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * unAssign KycRecord on Client
		 * @param		command UnAssignKycRecordFromClientCommand
		 * @exception	BusinessException
		 */
		public void unAssignKycRecord( UnAssignKycRecordFromClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignKycRecord(command.getClientId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign KycRecord on Client";
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}
		}
	

		/**
		 * add Account to Accounts
		 * @param		command AssignAccountsToClientCommand
		 * @exception	BusinessException
		 */
		public void addToAccounts( AssignAccountsToClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.addToAccounts(command.getClientId(), command.getAddTo());		}
			catch( Exception exc ) {
				final String msg = "Failed to add a Account as Accounts to Client" ;
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}

		}

		/**
		 * remove Account from Accounts
		 * @param		command RemoveAccountsFromClientCommand
		 * @exception	BusinessException
		 */
		public void removeFromAccounts( RemoveAccountsFromClientCommand command ) throws BusinessException {

			try {

				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.removeFromAccounts(command.getClientId(), command.getRemoveFrom());

			}
			catch( Exception exc ) {
				final String msg = "Failed to remove child using Id " + command.getClientId();
				LOGGER.warn(  msg, exc );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * add Document to Documents
		 * @param		command AssignDocumentsToClientCommand
		 * @exception	BusinessException
		 */
		public void addToDocuments( AssignDocumentsToClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.addToDocuments(command.getClientId(), command.getAddTo());		}
			catch( Exception exc ) {
				final String msg = "Failed to add a Document as Documents to Client" ;
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}

		}

		/**
		 * remove Document from Documents
		 * @param		command RemoveDocumentsFromClientCommand
		 * @exception	BusinessException
		 */
		public void removeFromDocuments( RemoveDocumentsFromClientCommand command ) throws BusinessException {

			try {

				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.removeFromDocuments(command.getClientId(), command.getRemoveFrom());

			}
			catch( Exception exc ) {
				final String msg = "Failed to remove child using Id " + command.getClientId();
				LOGGER.warn(  msg, exc );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * add Beneficiary to Beneficiaries
		 * @param		command AssignBeneficiariesToClientCommand
		 * @exception	BusinessException
		 */
		public void addToBeneficiaries( AssignBeneficiariesToClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.addToBeneficiaries(command.getClientId(), command.getAddTo());		}
			catch( Exception exc ) {
				final String msg = "Failed to add a Beneficiary as Beneficiaries to Client" ;
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}

		}

		/**
		 * remove Beneficiary from Beneficiaries
		 * @param		command RemoveBeneficiariesFromClientCommand
		 * @exception	BusinessException
		 */
		public void removeFromBeneficiaries( RemoveBeneficiariesFromClientCommand command ) throws BusinessException {

			try {

				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.removeFromBeneficiaries(command.getClientId(), command.getRemoveFrom());

			}
			catch( Exception exc ) {
				final String msg = "Failed to remove child using Id " + command.getClientId();
				LOGGER.warn(  msg, exc );
				throw new BusinessException( msg, exc );
			}
		}

		/**
		 * add Agreement to Agreements
		 * @param		command AssignAgreementsToClientCommand
		 * @exception	BusinessException
		 */
		public void addToAgreements( AssignAgreementsToClientCommand command ) throws BusinessException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.addToAgreements(command.getClientId(), command.getAddTo());		}
			catch( Exception exc ) {
				final String msg = "Failed to add a Agreement as Agreements to Client" ;
				LOGGER.warn( msg, exc );
				throw new BusinessException( msg, exc );
			}

		}

		/**
		 * remove Agreement from Agreements
		 * @param		command RemoveAgreementsFromClientCommand
		 * @exception	BusinessException
		 */
		public void removeFromAgreements( RemoveAgreementsFromClientCommand command ) throws BusinessException {

			try {

				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.removeFromAgreements(command.getClientId(), command.getRemoveFrom());

			}
			catch( Exception exc ) {
				final String msg = "Failed to remove child using Id " + command.getClientId();
				LOGGER.warn(  msg, exc );
				throw new BusinessException( msg, exc );
			}
		}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ClientEntityProjector projector;
	private final ClientValidator validator;
	private Client client 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(ClientService.class);
}
