/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
		package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Document business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Document related services in the case of a Document business related service failing.</li>
 * <li>Exposes a simpler, uniform Document interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Document business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class DocumentService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
		/**
		 * Default Constructor
		 */
    public DocumentService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

			this.identity		= identity;
			this.projector 		= new DocumentEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
											applicationContext.getBean(DocumentRepository.class) );
			this.validator		= applicationContext.getBean(DocumentValidator.class) ;
		}


		/**
		 * Creates the provided command.
		 *
		 * @param		command ${class.getCreateCommandAlias()}
		 * @exception    ProcessingException
		 * @exception	IllegalArgumentException
		 * @return		Document
		 */
			public Document createDocument( CreateDocumentCommand command )
    		throws ProcessingException, IllegalArgumentException {

			Document entity = new Document();

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

            entity.setDocumentId( command.getDocumentId() );
            entity.setTitle( command.getTitle() );
            entity.setFileName( command.getFileName() );
            entity.setReceivedDate( command.getReceivedDate() );
            entity.setDocumentType( command.getDocumentType() );

				// ------------------------------------------
				// persist a new one
				// ------------------------------------------
				entity = projector.create(entity);

				LOGGER.info( "done creating of Document {0} ", entity.toString() );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to create Document - " + exc;
				LOGGER.warn(  errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}

		/**
		 * Update the provided command.
		 * @param		command UpdateDocumentCommand
		 * @exception    ProcessingException
		 * @exception  	IllegalArgumentException
		 * @return		Document
		 */
		public Document updateDocument( UpdateDocumentCommand command )
    throws ProcessingException, IllegalArgumentException {

			Document entity = new Document();

			try {

				// --------------------------------------
				// validate
				// --------------------------------------
				validator.validate( command );

            entity.setDocumentId( command.getDocumentId() );
            entity.setTitle( command.getTitle() );
            entity.setFileName( command.getFileName() );
            entity.setReceivedDate( command.getReceivedDate() );
            entity.setClient( command.getClient() );
            entity.setKycRecord( command.getKycRecord() );
            entity.setAgreement( command.getAgreement() );
            entity.setDocumentType( command.getDocumentType() );

				// ------------------------------------------
				// persist an existing one
				// ------------------------------------------
				entity = projector.update(entity);

				LOGGER.info( "done saving of Document {0} ", entity.toString() );
			}
			catch (Exception exc) {
				final String errMsg = "Unable to save Document - " + exc;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}

			return entity;
		}

		/**
		 * Deletes the associatied value object
		 * @param		command DeleteDocumentCommand
		 * @exception 	ProcessingException
		 */
		public void delete( DeleteDocumentCommand command )
    throws ProcessingException, IllegalArgumentException {
			UUID id = null;

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				id = command.getDocumentId();

				// ------------------------------------------
				// delete the entity
				// ------------------------------------------
				projector.delete(id);

				LOGGER.info( "done deleting of Document {0} ", id );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to delete Document using Id = "  + id;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}
		}

		/**
		 * Method to retrieve the Document via DocumentFetchOneSummary
		 * @param 	summary DocumentFetchOneSummary
		 * @return 	DocumentFetchOneResponse
		 * @exception ProcessingException - Thrown if processing any related problems
		 * @exception IllegalArgumentException
		 */
    public Document getDocument( DocumentFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {

			if( summary == null )
				throw new IllegalArgumentException( "DocumentFetchOneSummary arg cannot be null" );

			Document entity = null;
			UUID id = summary.getDocumentId();

			try {
				// --------------------------------------
				// validate the fetch one summary
				// --------------------------------------
				validator.validate( summary );

				// --------------------------------------
				// find a Document using the provided id
				// --------------------------------------
				entity = projector.find( id );
			}
			catch( Exception exc ) {
				final String errMsg = "Unable to locate Document with id " + id;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}


		/**
		 * Method to retrieve a collection of all Documents
		 *
		 * @return 	List<Document>
		 * @exception ProcessingException Thrown if any problems
		 */
    public List<Document> getAllDocument() 
    throws ProcessingException {
			List<Document> list = null;

			try {
				list = projector.findAll( new FindAllDocumentQuery() );
			}
			catch( Exception exc ) {
				String errMsg = "Failed to get all Document";
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return list;
		}

		/**
		 * assign Client on Document
		 * @param		command AssignClientToDocumentCommand
		 * @exception	ProcessingException
		 */
		public void assignClient( AssignClientToDocumentCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignClient(command.getDocumentId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Client using id " + command.getDocumentId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign Client on Document
		 * @param		command UnAssignClientFromDocumentCommand
		 * @exception	ProcessingException
		 */
		public void unAssignClient( UnAssignClientFromDocumentCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignClient(command.getDocumentId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Client on Document";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	
		/**
		 * assign KycRecord on Document
		 * @param		command AssignKycRecordToDocumentCommand
		 * @exception	ProcessingException
		 */
		public void assignKycRecord( AssignKycRecordToDocumentCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignKycRecord(command.getDocumentId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get KycRecord using id " + command.getDocumentId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign KycRecord on Document
		 * @param		command UnAssignKycRecordFromDocumentCommand
		 * @exception	ProcessingException
		 */
		public void unAssignKycRecord( UnAssignKycRecordFromDocumentCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignKycRecord(command.getDocumentId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign KycRecord on Document";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	
		/**
		 * assign Agreement on Document
		 * @param		command AssignAgreementToDocumentCommand
		 * @exception	ProcessingException
		 */
		public void assignAgreement( AssignAgreementToDocumentCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignAgreement(command.getDocumentId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Agreement using id " + command.getDocumentId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign Agreement on Document
		 * @param		command UnAssignAgreementFromDocumentCommand
		 * @exception	ProcessingException
		 */
		public void unAssignAgreement( UnAssignAgreementFromDocumentCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignAgreement(command.getDocumentId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Agreement on Document";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final DocumentEntityProjector projector;
	private final DocumentValidator validator;
	private Document document 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(DocumentService.class);
}
