/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>FeeSchedule business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of FeeSchedule related services in the case of a FeeSchedule business related service failing.</li>
 * <li>Exposes a simpler, uniform FeeSchedule interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill FeeSchedule business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class FeeScheduleService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public FeeScheduleService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

		this.identity	= identity;

    	projector 		= new FeeScheduleEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(FeeScheduleRepository.class) );
	}


 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		FeeSchedule
    */
	public FeeSchedule createFeeSchedule( CreateFeeScheduleCommand command )
    throws ProcessingException, IllegalArgumentException {

		FeeSchedule entity = new FeeSchedule();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	FeeScheduleValidator.getInstance().validate( command );    

            entity.setFeeScheduleId( command.getFeeScheduleId() );
            entity.setName( command.getName() );
            entity.setRate( command.getRate() );
            entity.setMinimumFee( command.getMinimumFee() );
            entity.setFeeType( command.getFeeType() );
            entity.setBillingMethod( command.getBillingMethod() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of FeeSchedule {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create FeeSchedule - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateFeeScheduleCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		FeeSchedule
    */
    public FeeSchedule updateFeeSchedule( UpdateFeeScheduleCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    FeeSchedule entity = new FeeSchedule();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	FeeScheduleValidator.getInstance().validate( command );    

            entity.setFeeScheduleId( command.getFeeScheduleId() );
            entity.setName( command.getName() );
            entity.setRate( command.getRate() );
            entity.setMinimumFee( command.getMinimumFee() );
            entity.setAccounts( command.getAccounts() );
            entity.setBillingRuns( command.getBillingRuns() );
            entity.setFeeType( command.getFeeType() );
            entity.setBillingMethod( command.getBillingMethod() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of FeeSchedule {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save FeeSchedule - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteFeeScheduleCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteFeeScheduleCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	FeeScheduleValidator.getInstance().validate( command );    
        
        	id = command.getFeeScheduleId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of FeeSchedule {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete FeeSchedule using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the FeeSchedule via FeeScheduleFetchOneSummary
     * @param 	summary FeeScheduleFetchOneSummary 
     * @return 	FeeScheduleFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public FeeSchedule getFeeSchedule( FeeScheduleFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "FeeScheduleFetchOneSummary arg cannot be null" );
    	
    	FeeSchedule entity = null;
    	UUID id = summary.getFeeScheduleId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	FeeScheduleValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a FeeSchedule using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate FeeSchedule with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all FeeSchedules
     *
     * @return 	List<FeeSchedule> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<FeeSchedule> getAllFeeSchedule() 
    throws ProcessingException {
        List<FeeSchedule> list = null;

        try {        	
        	list = projector.findAll( new FindAllFeeScheduleQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all FeeSchedule";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }


    /**
     * add Account to Accounts 
     * @param		command AssignAccountsToFeeScheduleCommand
     * @exception	ProcessingException
     */     
	public void addToAccounts( AssignAccountsToFeeScheduleCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeeScheduleValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToAccounts(command.getFeeScheduleId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Account as Accounts to FeeSchedule" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Account from Accounts
     * @param		command RemoveAccountsFromFeeScheduleCommand
     * @exception	ProcessingException
     */     	
	public void removeFromAccounts( RemoveAccountsFromFeeScheduleCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeeScheduleValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromAccounts(command.getFeeScheduleId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getFeeScheduleId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}

    /**
     * add BillingRun to BillingRuns 
     * @param		command AssignBillingRunsToFeeScheduleCommand
     * @exception	ProcessingException
     */     
	public void addToBillingRuns( AssignBillingRunsToFeeScheduleCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeeScheduleValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToBillingRuns(command.getFeeScheduleId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a BillingRun as BillingRuns to FeeSchedule" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove BillingRun from BillingRuns
     * @param		command RemoveBillingRunsFromFeeScheduleCommand
     * @exception	ProcessingException
     */     	
	public void removeFromBillingRuns( RemoveBillingRunsFromFeeScheduleCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	FeeScheduleValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromBillingRuns(command.getFeeScheduleId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getFeeScheduleId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final FeeScheduleEntityProjector projector;
	private FeeSchedule feeSchedule 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(FeeScheduleService.class);
}
