/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>KycRecord business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of KycRecord related services in the case of a KycRecord business related service failing.</li>
 * <li>Exposes a simpler, uniform KycRecord interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill KycRecord business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class KycRecordService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public KycRecordService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new KycRecordEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(KycRecordRepository.class) );
	}

	
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		KycRecord
    */
	public KycRecord createKycRecord( CreateKycRecordCommand command )
    throws ProcessingException, IllegalArgumentException {

		KycRecord entity = new KycRecord();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	KycRecordValidator.getInstance().validate( command );    

            entity.setKycRecordId( command.getKycRecordId() );
            entity.setAssessmentDate( command.getAssessmentDate() );
            entity.setPepFlag( command.getPepFlag() );
            entity.setSourceOfWealth( command.getSourceOfWealth() );
            entity.setStatus( command.getStatus() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of KycRecord {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create KycRecord - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateKycRecordCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		KycRecord
    */
    public KycRecord updateKycRecord( UpdateKycRecordCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    KycRecord entity = new KycRecord();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	KycRecordValidator.getInstance().validate( command );    

            entity.setKycRecordId( command.getKycRecordId() );
            entity.setAssessmentDate( command.getAssessmentDate() );
            entity.setPepFlag( command.getPepFlag() );
            entity.setSourceOfWealth( command.getSourceOfWealth() );
            entity.setClient( command.getClient() );
            entity.setDocuments( command.getDocuments() );
            entity.setStatus( command.getStatus() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of KycRecord {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save KycRecord - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteKycRecordCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteKycRecordCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	KycRecordValidator.getInstance().validate( command );    
        
        	id = command.getKycRecordId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of KycRecord {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete KycRecord using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the KycRecord via KycRecordFetchOneSummary
     * @param 	summary KycRecordFetchOneSummary 
     * @return 	KycRecordFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public KycRecord getKycRecord( KycRecordFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "KycRecordFetchOneSummary arg cannot be null" );
    	
    	KycRecord entity = null;
    	UUID id = summary.getKycRecordId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	KycRecordValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a KycRecord using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate KycRecord with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all KycRecords
     *
     * @return 	List<KycRecord> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<KycRecord> getAllKycRecord() 
    throws ProcessingException {
        List<KycRecord> list = null;

        try {        	
        	list = projector.findAll( new FindAllKycRecordQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all KycRecord";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Client on KycRecord
     * @param		command AssignClientToKycRecordCommand	
     * @exception	ProcessingException
     */     
	public void assignClient( AssignClientToKycRecordCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	KycRecordValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignClient(command.getKycRecordId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Client using id " + command.getKycRecordId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Client on KycRecord
     * @param		command UnAssignClientFromKycRecordCommand
     * @exception	ProcessingException
     */     
	public void unAssignClient( UnAssignClientFromKycRecordCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	KycRecordValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignClient(command.getKycRecordId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Client on KycRecord";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	

    /**
     * add Document to Documents 
     * @param		command AssignDocumentsToKycRecordCommand
     * @exception	ProcessingException
     */     
	public void addToDocuments( AssignDocumentsToKycRecordCommand command ) throws ProcessingException {

		try {		
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	KycRecordValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.addToDocuments(command.getKycRecordId(), command.getAddTo());		}
		catch( Exception exc ) {
			final String msg = "Failed to add a Document as Documents to KycRecord" ; 
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}

	}

    /**
     * remove Document from Documents
     * @param		command RemoveDocumentsFromKycRecordCommand
     * @exception	ProcessingException
     */     	
	public void removeFromDocuments( RemoveDocumentsFromKycRecordCommand command ) throws ProcessingException {		

		try {
			
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	KycRecordValidator.getInstance().validate( command );    

	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.removeFromDocuments(command.getKycRecordId(), command.getRemoveFrom());

		}
		catch( Exception exc ) {
			final String msg = "Failed to remove child using Id " + command.getKycRecordId(); 
			LOGGER.warn(  msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final KycRecordEntityProjector projector;
	private KycRecord kycRecord 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(KycRecordService.class);
}
