/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>Proposal business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of Proposal related services in the case of a Proposal business related service failing.</li>
 * <li>Exposes a simpler, uniform Proposal interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill Proposal business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>07/31/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class ProposalService 
extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
    /** 
     * Default Constructor 
     */
    public ProposalService(CurrentIdentity identity)  {

		this.identity	= identity;
    	projector 		= new ProposalEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
							applicationContext.getBean(ProposalRepository.class) );
	}

	
 
   /**
    * Creates the provided command.
    * 
    * @param		command ${class.getCreateCommandAlias()}
    * @exception    ProcessingException
    * @exception	IllegalArgumentException
    * @return		Proposal
    */
	public Proposal createProposal( CreateProposalCommand command )
    throws ProcessingException, IllegalArgumentException {

		Proposal entity = new Proposal();

		try {
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	ProposalValidator.getInstance().validate( command );    

            entity.setProposalId( command.getProposalId() );
            entity.setProposalNumber( command.getProposalNumber() );
            entity.setCreatedDate( command.getCreatedDate() );
            entity.setRecommendationText( command.getRecommendationText() );
            entity.setStatus( command.getStatus() );
            entity.setExpectedRisk( command.getExpectedRisk() );
    	    
        	// ------------------------------------------
        	// persist a new one
        	// ------------------------------------------ 
    	    entity = projector.create(entity);
    	    
			LOGGER.info( "done creating of Proposal {0} ", entity.toString() );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to create Proposal - " + exc;
            LOGGER.warn(  errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }

   /**
    * Update the provided command.
    * @param		command UpdateProposalCommand
    * @exception    ProcessingException
    * @exception  	IllegalArgumentException
    * @return		Proposal
    */
    public Proposal updateProposal( UpdateProposalCommand command ) 
    throws ProcessingException, IllegalArgumentException {

	    Proposal entity = new Proposal();

    	try {       

			// --------------------------------------
        	// validate 
        	// --------------------------------------    	
        	ProposalValidator.getInstance().validate( command );    

            entity.setProposalId( command.getProposalId() );
            entity.setProposalNumber( command.getProposalNumber() );
            entity.setCreatedDate( command.getCreatedDate() );
            entity.setRecommendationText( command.getRecommendationText() );
            entity.setHousehold( command.getHousehold() );
            entity.setAdvisor( command.getAdvisor() );
            entity.setModelPortfolio( command.getModelPortfolio() );
            entity.setAccount( command.getAccount() );
            entity.setStatus( command.getStatus() );
            entity.setExpectedRisk( command.getExpectedRisk() );
        	
        	// ------------------------------------------
        	// persist an existing one
        	// ------------------------------------------ 
        	entity = projector.update(entity);
    	    
			LOGGER.info( "done saving of Proposal {0} ", entity.toString() );
    	}
        catch (Exception exc) {
            final String errMsg = "Unable to save Proposal - " + exc;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
    	
    	return entity;
    }
   
   /**
    * Deletes the associatied value object
    * @param		command DeleteProposalCommand
    * @exception 	ProcessingException
    */
    public void delete( DeleteProposalCommand command ) 
    throws ProcessingException, IllegalArgumentException {	
        UUID id = null;
        
    	try {  
			// --------------------------------------
        	// validate the command
        	// --------------------------------------    	
        	ProposalValidator.getInstance().validate( command );    
        
        	id = command.getProposalId();
        	
        	// ------------------------------------------
        	// delete the entity
        	// ------------------------------------------
        	projector.delete(id);

        	LOGGER.info( "done deleting of Proposal {0} ", id );

        }
        catch (Exception exc) {
            final String errMsg = "Unable to delete Proposal using Id = "  + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }
    }

    /**
     * Method to retrieve the Proposal via ProposalFetchOneSummary
     * @param 	summary ProposalFetchOneSummary 
     * @return 	ProposalFetchOneResponse
     * @exception ProcessingException - Thrown if processing any related problems
     * @exception IllegalArgumentException 
     */
    public Proposal getProposal( ProposalFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {
    	
    	if( summary == null )
    		throw new IllegalArgumentException( "ProposalFetchOneSummary arg cannot be null" );
    	
    	Proposal entity = null;
    	UUID id = summary.getProposalId();
    	
        try {
        	// --------------------------------------
        	// validate the fetch one summary
        	// --------------------------------------    	
        	ProposalValidator.getInstance().validate( summary );    
        	
        	// --------------------------------------
        	// find a Proposal using the provided id
        	// --------------------------------------
        	entity = projector.find( id );
        }
        catch( Exception exc ) {
            final String errMsg = "Unable to locate Proposal with id " + id;
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return entity;
    }


    /**
     * Method to retrieve a collection of all Proposals
     *
     * @return 	List<Proposal> 
     * @exception ProcessingException Thrown if any problems
     */
    public List<Proposal> getAllProposal() 
    throws ProcessingException {
        List<Proposal> list = null;

        try {        	
        	list = projector.findAll( new FindAllProposalQuery() );
        }
        catch( Exception exc ) {
            String errMsg = "Failed to get all Proposal";
            LOGGER.warn( errMsg, exc );
            throw new ProcessingException( errMsg, exc );
        }
        finally {
        }        
        
        return list;
    }

    /**
     * assign Household on Proposal
     * @param		command AssignHouseholdToProposalCommand	
     * @exception	ProcessingException
     */     
	public void assignHousehold( AssignHouseholdToProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignHousehold(command.getProposalId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Household using id " + command.getProposalId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Household on Proposal
     * @param		command UnAssignHouseholdFromProposalCommand
     * @exception	ProcessingException
     */     
	public void unAssignHousehold( UnAssignHouseholdFromProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignHousehold(command.getProposalId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Household on Proposal";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Advisor on Proposal
     * @param		command AssignAdvisorToProposalCommand	
     * @exception	ProcessingException
     */     
	public void assignAdvisor( AssignAdvisorToProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignAdvisor(command.getProposalId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Advisor using id " + command.getProposalId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Advisor on Proposal
     * @param		command UnAssignAdvisorFromProposalCommand
     * @exception	ProcessingException
     */     
	public void unAssignAdvisor( UnAssignAdvisorFromProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignAdvisor(command.getProposalId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Advisor on Proposal";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign ModelPortfolio on Proposal
     * @param		command AssignModelPortfolioToProposalCommand	
     * @exception	ProcessingException
     */     
	public void assignModelPortfolio( AssignModelPortfolioToProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignModelPortfolio(command.getProposalId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get ModelPortfolio using id " + command.getProposalId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign ModelPortfolio on Proposal
     * @param		command UnAssignModelPortfolioFromProposalCommand
     * @exception	ProcessingException
     */     
	public void unAssignModelPortfolio( UnAssignModelPortfolioFromProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignModelPortfolio(command.getProposalId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign ModelPortfolio on Proposal";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	
    /**
     * assign Account on Proposal
     * @param		command AssignAccountToProposalCommand	
     * @exception	ProcessingException
     */     
	public void assignAccount( AssignAccountToProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// best to validate the command now
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    

			// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.assignAccount(command.getProposalId(), command.getAssignment());
		    
		}
        catch( Throwable exc ) {
			final String msg = "Failed to get Account using id " + command.getProposalId();
			LOGGER.warn( msg );
			throw new ProcessingException( msg, exc );
        }
	}

    /**
     * unAssign Account on Proposal
     * @param		command UnAssignAccountFromProposalCommand
     * @exception	ProcessingException
     */     
	public void unAssignAccount( UnAssignAccountFromProposalCommand command ) throws ProcessingException {

		try {
			// --------------------------------------
	    	// validate the command
	    	// --------------------------------------    
	    	ProposalValidator.getInstance().validate( command );    
	
	    	// --------------------------------------
	    	// delegate to the projector
	    	// --------------------------------------    	    	
	    	projector.unAssignAccount(command.getProposalId());
		}
		catch( Exception exc ) {
			final String msg = "Failed to unassign Account on Proposal";
			LOGGER.warn( msg, exc );
			throw new ProcessingException( msg, exc );
		}
	}
	





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final ProposalEntityProjector projector;
	private Proposal proposal 	= null;
	private CurrentIdentity identity			= null;
    private static final Logger LOGGER 			=  LoggerFactory.getLogger(ProposalService.class);
}
