/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Spring Boot 3.5
 *
 * Domain Model:
 * ${blueprint.getModelMetadata().getName()}
 *
 * Do not edit manually.
 ********************************************************
 * Turnstone Biologics Confidential
 *
 * 2026 Turnstone Biologics
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *       Turnstone Biologics - General Release
 */
		package com.harbormaster.service;

import java.io.IOException;
import java.util.*;
import java.util.concurrent.*;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.ApplicationContext;


import com.harbormaster.api.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;
import com.harbormaster.repository.*;
import com.harbormaster.validator.*;
import com.harbormaster.projector.*;
import com.harbormaster.security.*;

/**
 *
 * <h2>RebalancePlan business delegate</h2>
 *
 * <p>
 * This class implements the Business Delegate design pattern for the purpose of:
 * </p>
 * <ol>
 * <li>Reducing coupling between the business tier and a client of the business tier by hiding all business-tier implementation details</li>
 * <li>Improving the available of RebalancePlan related services in the case of a RebalancePlan business related service failing.</li>
 * <li>Exposes a simpler, uniform RebalancePlan interface to the business tier, making it easy for clients to consume a simple Java object.</li>
 * <li>Hides the communication protocol that may be required to fulfill RebalancePlan business related services.</li>
 * </ol>
 *
  * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Spring Boot 3.5</td></tr>
 *          <tr><td>published</td><td>08/05/2026</td></tr>
 *          <tr><td>design pattern</td><td>ServiceLayer</td></tr>
 *          <tr><td>architecture style</td><td>Layered</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Wealth Management Capabilities Model</td></tr>
 *          <tr><td>description</td><td>Canonical HCIDL model for wealth management covering advisory, portfolio management, trading, client servicing, billing, and compliance.</td></tr>
 *          <tr><td>industry</td><td>Financial Services</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services</h3>
 *		<ul>
 * 		<li>QueryGateway</li>
 * 		<li>CommandGateway</li>
 *		<li>QueryUpdateEmitter</li>
 *		</ul>
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@Service
public class RebalancePlanService 
		extends BaseService {
//************************************************************************
// Public Methods
//************************************************************************
		/**
		 * Default Constructor
		 */
    public RebalancePlanService(CurrentIdentity identity,
				ApplicationContext applicationContext)  {

			this.identity		= identity;
			this.projector 		= new RebalancePlanEntityProjector( applicationContext.getBean(ProjectorRegistry.class),
											applicationContext.getBean(RebalancePlanRepository.class) );
			this.validator		= applicationContext.getBean(RebalancePlanValidator.class) ;
		}


		/**
		 * Creates the provided command.
		 *
		 * @param		command ${class.getCreateCommandAlias()}
		 * @exception    ProcessingException
		 * @exception	IllegalArgumentException
		 * @return		RebalancePlan
		 */
			public RebalancePlan createRebalancePlan( CreateRebalancePlanCommand command )
    		throws ProcessingException, IllegalArgumentException {

			RebalancePlan entity = new RebalancePlan();

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

            entity.setRebalancePlanId( command.getRebalancePlanId() );
            entity.setPlanDate( command.getPlanDate() );
            entity.setStatus( command.getStatus() );
            entity.setMethod( command.getMethod() );

				// ------------------------------------------
				// persist a new one
				// ------------------------------------------
				entity = projector.create(entity);

				LOGGER.info( "done creating of RebalancePlan {0} ", entity.toString() );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to create RebalancePlan - " + exc;
				LOGGER.warn(  errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}

		/**
		 * Update the provided command.
		 * @param		command UpdateRebalancePlanCommand
		 * @exception    ProcessingException
		 * @exception  	IllegalArgumentException
		 * @return		RebalancePlan
		 */
		public RebalancePlan updateRebalancePlan( UpdateRebalancePlanCommand command )
    throws ProcessingException, IllegalArgumentException {

			RebalancePlan entity = new RebalancePlan();

			try {

				// --------------------------------------
				// validate
				// --------------------------------------
				validator.validate( command );

            entity.setRebalancePlanId( command.getRebalancePlanId() );
            entity.setPlanDate( command.getPlanDate() );
            entity.setPortfolio( command.getPortfolio() );
            entity.setProposedOrders( command.getProposedOrders() );
            entity.setAdvisor( command.getAdvisor() );
            entity.setStatus( command.getStatus() );
            entity.setMethod( command.getMethod() );

				// ------------------------------------------
				// persist an existing one
				// ------------------------------------------
				entity = projector.update(entity);

				LOGGER.info( "done saving of RebalancePlan {0} ", entity.toString() );
			}
			catch (Exception exc) {
				final String errMsg = "Unable to save RebalancePlan - " + exc;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}

			return entity;
		}

		/**
		 * Deletes the associatied value object
		 * @param		command DeleteRebalancePlanCommand
		 * @exception 	ProcessingException
		 */
		public void delete( DeleteRebalancePlanCommand command )
    throws ProcessingException, IllegalArgumentException {
			UUID id = null;

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				id = command.getRebalancePlanId();

				// ------------------------------------------
				// delete the entity
				// ------------------------------------------
				projector.delete(id);

				LOGGER.info( "done deleting of RebalancePlan {0} ", id );

			}
			catch (Exception exc) {
				final String errMsg = "Unable to delete RebalancePlan using Id = "  + id;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}
		}

		/**
		 * Method to retrieve the RebalancePlan via RebalancePlanFetchOneSummary
		 * @param 	summary RebalancePlanFetchOneSummary
		 * @return 	RebalancePlanFetchOneResponse
		 * @exception ProcessingException - Thrown if processing any related problems
		 * @exception IllegalArgumentException
		 */
    public RebalancePlan getRebalancePlan( RebalancePlanFetchOneSummary summary ) 
    throws ProcessingException, IllegalArgumentException {

			if( summary == null )
				throw new IllegalArgumentException( "RebalancePlanFetchOneSummary arg cannot be null" );

			RebalancePlan entity = null;
			UUID id = summary.getRebalancePlanId();

			try {
				// --------------------------------------
				// validate the fetch one summary
				// --------------------------------------
				validator.validate( summary );

				// --------------------------------------
				// find a RebalancePlan using the provided id
				// --------------------------------------
				entity = projector.find( id );
			}
			catch( Exception exc ) {
				final String errMsg = "Unable to locate RebalancePlan with id " + id;
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return entity;
		}


		/**
		 * Method to retrieve a collection of all RebalancePlans
		 *
		 * @return 	List<RebalancePlan>
		 * @exception ProcessingException Thrown if any problems
		 */
    public List<RebalancePlan> getAllRebalancePlan() 
    throws ProcessingException {
			List<RebalancePlan> list = null;

			try {
				list = projector.findAll( new FindAllRebalancePlanQuery() );
			}
			catch( Exception exc ) {
				String errMsg = "Failed to get all RebalancePlan";
				LOGGER.warn( errMsg, exc );
				throw new ProcessingException( errMsg, exc );
			}
			finally {
			}

			return list;
		}

		/**
		 * assign Portfolio on RebalancePlan
		 * @param		command AssignPortfolioToRebalancePlanCommand
		 * @exception	ProcessingException
		 */
		public void assignPortfolio( AssignPortfolioToRebalancePlanCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignPortfolio(command.getRebalancePlanId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Portfolio using id " + command.getRebalancePlanId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign Portfolio on RebalancePlan
		 * @param		command UnAssignPortfolioFromRebalancePlanCommand
		 * @exception	ProcessingException
		 */
		public void unAssignPortfolio( UnAssignPortfolioFromRebalancePlanCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignPortfolio(command.getRebalancePlanId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Portfolio on RebalancePlan";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	
		/**
		 * assign Advisor on RebalancePlan
		 * @param		command AssignAdvisorToRebalancePlanCommand
		 * @exception	ProcessingException
		 */
		public void assignAdvisor( AssignAdvisorToRebalancePlanCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// best to validate the command now
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.assignAdvisor(command.getRebalancePlanId(), command.getAssignment());

			}
			catch( Throwable exc ) {
				final String msg = "Failed to get Advisor using id " + command.getRebalancePlanId();
				LOGGER.warn( msg );
				throw new ProcessingException( msg, exc );
			}
		}

		/**
		 * unAssign Advisor on RebalancePlan
		 * @param		command UnAssignAdvisorFromRebalancePlanCommand
		 * @exception	ProcessingException
		 */
		public void unAssignAdvisor( UnAssignAdvisorFromRebalancePlanCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.unAssignAdvisor(command.getRebalancePlanId());
			}
			catch( Exception exc ) {
				final String msg = "Failed to unassign Advisor on RebalancePlan";
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}
	

		/**
		 * add Order to ProposedOrders
		 * @param		command AssignProposedOrdersToRebalancePlanCommand
		 * @exception	ProcessingException
		 */
		public void addToProposedOrders( AssignProposedOrdersToRebalancePlanCommand command ) throws ProcessingException {

			try {
				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.addToProposedOrders(command.getRebalancePlanId(), command.getAddTo());		}
			catch( Exception exc ) {
				final String msg = "Failed to add a Order as ProposedOrders to RebalancePlan" ;
				LOGGER.warn( msg, exc );
				throw new ProcessingException( msg, exc );
			}

		}

		/**
		 * remove Order from ProposedOrders
		 * @param		command RemoveProposedOrdersFromRebalancePlanCommand
		 * @exception	ProcessingException
		 */
		public void removeFromProposedOrders( RemoveProposedOrdersFromRebalancePlanCommand command ) throws ProcessingException {

			try {

				// --------------------------------------
				// validate the command
				// --------------------------------------
				validator.validate( command );

				// --------------------------------------
				// delegate to the projector
				// --------------------------------------
				projector.removeFromProposedOrders(command.getRebalancePlanId(), command.getRemoveFrom());

			}
			catch( Exception exc ) {
				final String msg = "Failed to remove child using Id " + command.getRebalancePlanId();
				LOGGER.warn(  msg, exc );
				throw new ProcessingException( msg, exc );
			}
		}





//************************************************************************
// Attributes
//************************************************************************
	@Autowired
    private final RebalancePlanEntityProjector projector;
	private final RebalancePlanValidator validator;
	private RebalancePlan rebalancePlan 	= null;
	private CurrentIdentity identity			= null;
	private static final Logger LOGGER 			=  LoggerFactory.getLogger(RebalancePlanService.class);
}
